### ISSUE TITLE
Command bind issue

### ISSUE THREAD

**Issue by PaddyWagon** [RockinChaos/ItemJoin#105]
The item will lose its command bind after being moved to a different inventory slot, or after a certain amount of time. 

I'm using 1.11.2 with the most recent ItemJoin spigot release. 

I have set ItemJoin-Specific-Items to false as well, so I'm not sure what the issue could be. 

Regards, 
Patrick

**Comment by RockinChaos** [comment]
can you post your items.yml and config.yml in a pastebin.com please?

**Comment by PaddyWagon** [comment]
https://hastebin.com/aziyiruwuq.coffeescript
https://hastebin.com/juhusisexi.scala

**Comment by RockinChaos** [comment]
Sweet I will begin testing and let you know what I find.

**Comment by RockinChaos** [comment]
Issue fixed in v4.0 I am having a few bug testers test the new version and I will release it soon. (next week or two at the most).

The reason for this bug is another plugin is updating the items and I had a bad snippet of code that would make ItemJoin forget that they are actually ItemJoin items making ItemJoin not recognize them when you tried to right click them to execute a command.

**Comment by RockinChaos** [comment]
v4.0 has been released fixing this issue.

You can click here to download; https://www.spigotmc.org/resources/itemjoin.12661/download?version=168950
