### ISSUE TITLE
Missing global settings in v4.0.

### ISSUE THREAD

**Issue by mibby** [RockinChaos/ItemJoin#110]
ItemJoin dev 12

These settings from v3.x don't seem to have a replacement equivalent in v4.0.
```
    clear-only-itemjoin-on-join: true
    clear-only-itemjoin-on-world-change: true
```

**Comment by RockinChaos** [comment]
Nobody has asked to bug test it yet so I haven't submitted any documentation but there is indeed an equivalent since I use it a lot on my server.

In the config.yml where it says;
Clear-Items: All

replace All with ItemJoin it should look like
Clear-Items: ItemJoin

That changes it from clearing all items to just ItemJoin items and all you have to do is set the clear on world change and or clear on join below it to true.

**Comment by RockinChaos** [comment]
Here is a current documentation for the planned release; https://www.spigotmc.org/wiki/v4-0-changes/
