### ISSUE TITLE
Vault economy issue.

### ISSUE THREAD

**Issue by KechuFonzo** [RockinChaos/ItemJoin#114]
Hello, when I join to the server I recive all the items(3)  but only one works (servidores id:paper), and when I do a click with the 2 that doesn't work (rangos id:diamond and contactos id:399) there is the next error:
https://pastebin.com/ACxMdtLw
 Sorry if you don´t understand me I'm argentinian. This Is my item.yml:
https://pastebin.com/5cQnwG8D
I'm using spigot 1.8.8.R0.1 and plugin version 4.1
Thanks You For Your Time!

**Comment by RockinChaos** [comment]
Issue is with vault, Already resolved the problem just waiting for an update. I will have a fix out for those who keep setting commands-cost to zero instead of removing it.
**Easy fix is to just remove the commands-cost: 0**
You don't need that line, you can remove any line that is on an ItemJoin item except the ID and slot#.

**Comment by RockinChaos** [comment]
Issue is fixed in v4.2 you can get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=171839

**Comment by KechuFonzo** [comment]
Thanks hoy! You are awesome!!
