### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ProDash1998** [RockinChaos/ItemJoin#130]
`[ItemJoin] Checking for updates...
[13:37:02 INFO]: [ItemJoin] An error has occured when checking the plugin version!
[13:37:02 INFO]: [ItemJoin] Please contact the plugin developer!
[13:37:02 INFO]: [ItemJoin] Error is java.lang.NullPointerException C13904
[13:37:02 INFO]: [ItemJoin] has been Enabled!`

Server wersion 1.12.1
version plugin lastes

**Comment by RockinChaos** [comment]
Looking into it now, something changed in the latest version that broke it.

**Comment by Zukeow** [comment]
Hello bro, sI just wanted to ask what is the permission so that when a new user gives you the specified item, it's only given to the op's and I want it to be given to everyone

**Comment by RockinChaos** [comment]
@Zukeow 
Oh I think you are meaning only op's are getting the items upon joining. 

If you have a permission-node defined for the item that trumps the default permissions so make sure if you do have one you use those.

You must have a permissions plugin installed.

I installed ItemJoin but I am not getting any items!
Example; deoped players or players with the default permissions plugin group rank do not get the items when they join but oped players do.

This is because you didn't setup the permissions correctly. If you have a permissions-node defined under the items you must use that permission in the permissions group. Otherwise you have to use one of the two default permissions;

Code (Text):
itemjoin.WorldName.Name:
description: Replace Name with the name of the specified item and WorldName with name of world to receive that item.
default: false

itemjoin.WorldName.*:
description: Gives permission to get all items from specified world.
default: false

(I recommend itemjoin.worldname.* as it would be easier)

or you can set your own custom permission nodes for each item. See; https://www.spigotmc.org/wiki/itemjoin-getting-started/
just add permission-node: 'itemjoin.ultra' to your item. You can change the permission node to whatever you want just add the permissions to a permissions plugin afterwards.

Remember permissions are also case sensitive, even the world name! 
This is because of java restrictions and hopefully will change in the future. Sometimes certain permissions plugins fix this but in reality it depends on the permissions plugin you use.

**Comment by Zukeow** [comment]
This is the permit? Is that I'm new to this plugins setup and it makes me very complicated :(
http://imgur.com/a/7kxE0

**Comment by RockinChaos** [comment]
if Homestead is the name of the world then yes. Note; the world is case sensitive!

**Comment by RockinChaos** [comment]
Check for update bug fixed as of v4.5 and has been released here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=185550
