### ISSUE TITLE
Update Ticks

### ISSUE THREAD

**Issue by PinoyLifeCraft** [RockinChaos/ItemJoin#143]
Hello there @RockinChaos,

I believe what causes my 
![2017-10-01_07 26 58](https://user-images.githubusercontent.com/13610530/31050385-bb73646c-a5fd-11e7-9d57-9736172d903c.png)
is the item name it's because the items contain the online status at the items, every time I join to my server I got that warning 🙁 If possible can you add updateticking for the item?
This is what the people see in the items
![2](https://user-images.githubusercontent.com/13610530/31050415-8041f3d0-a5fe-11e7-9529-a372209ea409.png)
Then that should update when the online move forward 😂
And also when I click the "Coming Soon Server" (items) they are not working I mean the command is not running Uhm I don't know 😂  I think it works but only the commands that I set or I need to use Normal Player to work?
[Items.yml](https://hastebin.com/orosihihez.cs)
Plugin Version: ItemJoin v4.5
Server Spigot: 1.12.1

**Comment by RockinChaos** [comment]
It's currently not as simple to implement as I would like due to how spigots API is handled, however, I have been working on getting out for ItemJoin v4.6 or at the latest v4.7. I will keep you posted as I progress on this. I will have to make it so items frequently update when an event is triggered.

The only way currently fix this until v4.6 is to set clear inventory on join to true (ItemJoin only items of course).

**Comment by RockinChaos** [comment]
**Added in the latest snapshot.**

However please note; This is VERY experimental right now, it seems to be working okay but there has been no major bug testing on it.

<a href="https://imgur.com/idPqepb"><img src="https://i.imgur.com/idPqepb.png" title="source: imgur.com" /></a>

I still need to test; 
How the server is affected by multiple users online (a regular server load test).
As well as to get a timings report on this.

My goal is to get this all double checked so I feel confident in releasing this for ItemJoin v4.6. If anything major is reported then it will be pushed until v4.7. However, my goal is to push this for v4.6

If you wish to test this feel free to pick up the snapshot here; http://ci.craftationgaming.com/job/ItemJoin/
Please do not use this on a production server, only use this on a testing server, otherwise do so at your own risk.


Next to do on this is add a way to animate the Item's Name and Lore. Currently, placeholders are just updated, it would be cool to have randomly changing names and lore. Such as different colors or different messages etc.

**Comment by PinoyLifeCraft** [comment]
Oh so you've been asking me to test it sorry 😂 I was inactive but as I said "I will not use snapshot :( "

**Comment by PinoyLifeCraft** [comment]
Really sorry :( hope you'll understand :)

**Comment by RockinChaos** [comment]
I wasnt asking just saying if you want to. Its all good. I have been having a team bug test this over the past few weeks.

**Comment by RockinChaos** [comment]
Added as of ItemJoin v4.6 and it has been released!
Get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=202495

Please read the changelog as the documentation has not been updated yet; https://www.spigotmc.org/wiki/recent-changes
