### ISSUE TITLE
Permission problem ?

### ISSUE THREAD

**Issue by Promisize** [RockinChaos/ItemJoin#145]
Hello, sorry for my English, i'm French, so with my friend we trying to give the items at players when they connect to my server, but nothing... They have no item in the slot of inventory, and when we give all permissions at players, that work. And what the difference between the permission.all and * ? Because the permission.all don't give items, and permissions* give items. We don't arrived to delete permissions and make the items stay in the slot of inventory, please help :(

**Comment by RockinChaos** [comment]
Sorry if I don't answer this correctly, it is hard to understand your translation to English. Let me know if its not.

1.) There is no difference between itemjoin.all and itemjoin.* the only thing is that itemjoin.all was not fully implemented yet and does not work.

2.) It sounds like you are having permissions problems on getting items upon joining, I think this should help you. Also If the player is OP they receive the items right? Just not de-opped players, if oped players do not receive the items then it's a config issue and not a permissions issue.

**I installed ItemJoin but I am not getting any items!**
Example; deoped players or players with the default permissions plugin group rank do not get the items when they join but oped players do.

This is because you didn't setup the permissions correctly. If you have a permissions-node defined under the items you must use that permission in the permissions group. Otherwise, you have to use one of the two default permissions;

itemjoin.WorldName.Name:
description: Replace Name with the name of the specified item and WorldName with name of world to receive that item.
default: false

itemjoin.WorldName.*:
description: Gives permission to get all items from specified world.
default: false

(I recommend itemjoin.worldname.* as it would be easier)

or you can set your own custom permission nodes for each item. See; https://www.spigotmc.org/wiki/itemjoin-getting-started/
just add permission-node: 'itemjoin.ultra' to your item. You can change the permission node to whatever you want just add the permissions to a permissions plugin afterwards.

Remember permissions are also case sensitive, even the world name!
This is because of java restrictions and hopefully will change in the future. Sometimes certain permissions plugins fix this but in reality it depends on the permissions plugin you use.


**If this still does not fix your issue please reply with the name of the permissions plugin you are using.**

**Comment by TheCreeperESP** [comment]
Where i have to put "itemjoin.WorldName.*"?
I'm Spanish ✌️
