### ISSUE TITLE
Clear ALL items on specified worlds.

### ISSUE THREAD

**Issue by Nesseley** [RockinChaos/ItemJoin#149]
Running newest version of the plugin. 1.12.2 Spigot.

I have a hub using multiverse where i give players a kit for elytra, I want the elytra to be cleared on join.

Problem: When enabling clear items on join (ALL, as the elytra is a kit-item, not ItemJoin) it will clear no matter what world you login in. Players will clear their survival inventory if the setting is set to ALL.

Config.yml : enabled-worlds: hub2
I've tried using PerWorldPlugins and only have ItemJoin be enabled in world:hub2 but it's still clearing survival-inventory on join.

Possible sulution? make the plugin check what world you login to before you clear the inventory.

**Comment by RockinChaos** [comment]
Hmmm if hub2 is set for enabled-worlds ItemJoin disables its self from any worlds that are not listed. Its possible that its another plugin conflicting with ItemJoin.

Can you please post your whole config.yml in a pastebin.com so I can load it up on my test server.

**Comment by Nesseley** [comment]
Config: https://pastebin.com/HtsShZrB
version 4.5

**Comment by RockinChaos** [comment]
Ahhh I see you are using the #// **Global** Clear Items for ItemJoin. //# as shown in the config. If any of those settings are set to true it does those settings in all worlds, hence [Global].

The enabled-worlds you were talking about were for #// Global **Commands** for ItemJoin on join, these commands are executed by console. //#

Currently, it is not possible to specify what worlds you want to clear ALL items on, which is a mistake on my part. I will add this in ItemJoin v4.6 which is due to release by January 1st. (next couple of days). I will also post back once I have pushed a snapshot with this request in it, which should be later today. Thanks for bringing this to my attention!

**Comment by RockinChaos** [comment]
I have completed this and it will be pushed in the next snapshot. This new feature will be available when v4.6 of ItemJoin is released in the next few days.

What I have done; I have changed;
```
Clear-On-Join: true
Clear-On-WorldChanged: false
```

**to**

```
Clear-On-Join: world
Clear-On-WorldChanged: world, world_nether
```

You can still add the boolean, only if you want it to be for every single world. However, now which is now shown in the default config files, you can define the worlds as shown for each of the options. Or just set it to false to disable the option in general.

If you have any questions feel free to let me know.

**Comment by Nesseley** [comment]
This is awesome! Thanks for fixing this problem so fast! 
Looking forward to the new update, also happy new year! :)

**Comment by RockinChaos** [comment]
Added as of ItemJoin v4.6 and it has been released!
Get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=202495

Please read the changelog as the documentation has not been updated yet; https://www.spigotmc.org/wiki/recent-changes
