### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by dav64** [RockinChaos/ItemJoin#15]
Hello, I have encoding problem with items names or lores.
when i use accented letters or symbols in them, i see some weird characters in game like Ã© instead.

Thanks!

**Comment by RockinChaos** [comment]
Can you paste each symbol you are trying to use that are causing problems please?

**Comment by dav64** [comment]
Tested with french accents like é è à 
I tried also with ♫

**Comment by RockinChaos** [comment]
Sorry, I have been really busy with personal issues lately. I will look at this first thing when I get time.

**Comment by RockinChaos** [comment]
No idea how but this is fixed in ItemJoin v2.7! Just randomly fixed its self when I went to test it. I was aware this was an issue but the second time I go to test it its fixed lol. Must be the big re-code I did. Since I am now using a lot of different handlers.


**I plan to release ItemJoin v2.7 tomorrow so look out for it!**
