### ISSUE TITLE
Item Join Preventing Pick ups and Drops

### ISSUE THREAD

**Issue by Sunboyz21** [RockinChaos/ItemJoin#169]
1.) The version of the Resource. 
    Latest
2.) Version of the Spigot / Craftbukkit / Cauldron / ETC.
git-Spigot-1.7.9-R0.2-208-ge0f2e95 (1.7 to 1.8)
3.) What is the problem that you are having?
   Item join is causing lag and preventing pick ups and drops of items not declared in the config and in a different world separate from the 'Lobby'. Pick ups are enabled. When I drop items, they just continuously teleport up and then drop, this stops after I remove ItemJoin (Images: https://imgur.com/a/xayUp)
4.) Post all your YAML / Configuration files, please include a Pastebin.com link.
Config.yml: https://pastebin.com/KUSbqLjz
items.yml: https://pastebin.com/ApnXWV4z
5.) Post any error codes found in your console window if it pertains to this issue, please include a Pastebin.com link.
None

**Comment by Sunboyz21** [comment]
Here are some more images. This issue is gone as soon as I remove itemjoin
![2018-03-24_11 06 28](https://user-images.githubusercontent.com/26012347/37867343-0d976d4e-2f54-11e8-9cc8-7290bd33528d.png)
![2018-03-24_11 06 26](https://user-images.githubusercontent.com/26012347/37867344-0e0f1f9c-2f54-11e8-8486-b5025b9ab3e0.png)

**Comment by RockinChaos** [comment]
Just tested with the configs you are using and I am not able to replicate this problem being related to ItemJoin. I tested all versions between mc 1.7-1.12.2 (even mc 1.7.9 & 1.8).

1.) Did you use plugman to disable ItemJoin via /plugman disable ItemJoin (Instead of restarting the server which could make the issue go away).

2.) What is your allocation to your server (Amount of ram).

3.) Can you provide some timings while this issue is happening? /timings on then /timings paste and send me the link.

4.) How many plugins do you have on your server? I'm starting to wonder if your server has just reached its cap with how many plugins it can handle with the amount of ram it has.

Sorry for the late reply. I was 1 am when you sent the help request for me so I was passed out lol.

**Comment by Sunboyz21** [comment]
1, I am not using plugman and have restarted the server multiple times.

2. 2.5 gb of ram

3. I will send you this once I have access to my pc in about 30min

4. I have 15 plugins, I have not reached the cap because if I remove item join and add different plugins that are more intensive (scoreboard), it runs fine (19.92tps)

**Comment by RockinChaos** [comment]
Status: Was continued on discord, was found out to be an issue with that specific server and was either a setting or another plugin causing this issue.

Feel free to re-open this if you still need help or message again on discord.
