### ISSUE TITLE
Clickable items in inventory

### ISSUE THREAD

**Issue by Y3cy** [RockinChaos/ItemJoin#172]
Hi,

How do you make an item clickable and executes the command while it is not in the hotbar but is on slot 16 as example.

**Comment by RockinChaos** [comment]
So in your case since you want to be able to click it with the inventory open, you would be using;
`commands-type: inventory`

Example item;
```items:
  ultra-item:
    id: DIAMOND_SWORD
    slot: 0
    commands:
      inventory:
        - 'console: gamemode 2 %player%'
        - 'message: &eYou have been set to adventure mode.'
    commands-type: inventory
    commands-sound: BLOCK_NOTE_PLING
    enabled-worlds: world```

Let me know if this worked for you.

**Comment by Y3cy** [comment]
`    sabh:
      id: EMERALD
      slot: 16
      name: '&6Auction House'
      data-value: 0
      count: 1
      lore:
        - '&7 '
      commands:
        inventory:
          - 'player: ah'
      commands-type: inventory
      itemflags:
        - 'self-drops'
        - 'world-changed'
        - 'unbreakable'
        - 'hide-attributes'
        - 'inventory-modify'
        - 'death-drops'
        - 'self-drops'
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
        - 'CreativeBypass'
        - 'cancel-events'`

Doesn't seem to work.

**Comment by RockinChaos** [comment]
Try this as your items.yml;
The spacing seemed messed up also the item you created is vastly outdated, so much so that itemflags are no longer listed like that they are now separated by commas. Also respawn, world-changed and join triggers are now a thing.

Please make sure you are up to date on ItemJoin running either v4.7 or v4.8-SNAPSHOT as the inventory commands were not added until like v4.5.

Let me know if this helped.

**Comment by RockinChaos** [comment]
Not sure if this ended up helping you, v4.8 has been released and contains a lot of bug fixes if you are interested; https://www.spigotmc.org/resources/itemjoin.12661/download?version=223327

If you are still having issues feel free to re-open this issue.
