### ISSUE TITLE
Map disappearing bug

### ISSUE THREAD

**Issue by ShawnPR1** [RockinChaos/ItemJoin#174]
1.) Version of ItemJoin (outdated with 1 version I know): 4.8-SNAPSHOT
2.) Version of Spigot: 1.12.2-R0.1-SNAPSHOT
3.) What is the problem that you are having?
I have a custom map set up for a specific world that just shows an image with text on it. It works perfectly. Here's the problem, however:
Let's say there are 2 players in that world. If any one of them leave that world, the other player's map image disappears. They still hold the map, but there is no image at all.
4.) Config files: I do not want to post them here, plus I know this is not the config causing the issue.
5.) Error codes: There are no errors in the console at all.

I hope I've supplied enough information and am not posting a useless issue here. This plugin is amazing and I value your time.

**Comment by RockinChaos** [comment]
Thanks so much, it actually means a lot. Let's see if we can get this issue resolved swiftly.

I would recommend first updating to the release version of v4.8 as I actually think it was a certain snapshot in v4.8 that resolved this issue.

Let me know if this issue still persists after this, if it does I might need a snippet of the map item privately messaged to me as I am going to need to get an idea on how you are implementing the path since the specific way you do it might have found a weak spot in the image processing that I will have to fix.

Also, I have to ask if all users are using a single map image or are they all different?
Also, do you have multiple map items using different images or just one?

Also! A major thing is to make sure you have set up the map-id under the item! This was a major thing back in v4.6 I had to add to fix a similar issue back then.

Messing around with this number might resolve your issue as other plugins could be utilizing that specific map-id. (Even if it's not for a map item, it's more just a pre-load for the server's system).
`    map-id: 1`

**Comment by ShawnPR1** [comment]
1) All users are using the same map image
2) I only have once custom map image being used throughout the entire server
3) Size of the image is exactly 126x126 (this happened when the image was 128x128 as well)

I have changed the map-id quite a few times. I'll update to the latest version when I have time and I'll let you know.

The strangest thing is that the image works perfectly, but as soon as another player teleports out of the world, the player still in that world's map image disappears and they just hold an empty map in their hand. Might be because I don't have the latest version though so as I said above I'll update as soon as I can and let you know.

Thanks for the quick response!

**Comment by ShawnPR1** [comment]
I've tested it with the newest version, but it's still happening. The map still disappears for the player in the world as soon as another player leaves the world.

**Comment by RockinChaos** [comment]
Okay, I will test this again and see if I can come up with some results.

**Comment by RockinChaos** [comment]
Okay so I have done some extensive testing on this over the past week and I am unable to replicate this issue. I have tried exactly what you said as well as trying it on previous versions of spigot & craftbukkit with no luck.

Would you mind sending me your map item so I can see how it is formatted in the config? Its possible a certain itemflag or sequence is causing the issue.
