### ISSUE TITLE
ItemJoin - Clearing Items

### ISSUE THREAD

**Issue by dlndcrdso** [RockinChaos/ItemJoin#176]
1.) The version of the Resource.
    v4.8
    Config-Version: 6
2.) Version of the Spigot / Craftbukkit / Cauldron / ETC.
    1.8.9 Spigot / Bukkit Server
3.) What is the problem that you are having?
    I receive my items as normal on the hub world but when I got into any other world, put stuff in my inv and log out (of the world I'm in) I lose all the items that were in my inv in the world I logged out of.
Example: Log in (hub) go on survival, use kits (put stuff in my inv), log out (while in survival world), log back in (start in hub), go back to survival world, my inventory is completely empty.
4.) Post all your YAML / Configuration files, please include a Pastebin.com link.
    config.yml: https://pastebin.com/9UfWzuHg
    items.yml: https://pastebin.com/qRQDNfqh
5.) Post any error codes found in your console window if it pertains to this issue, please include a Pastebin.com link.
   Console Error: https://pastebin.com/4EKtxacL

**Comment by RockinChaos** [comment]
You have clear on world changed set in the config.yml so once you change worlds it will clear your inventory. I would recommend setting this to false and testing if this resolves your issue.

**Comment by dlndcrdso** [comment]
Still clears the items

**Comment by RockinChaos** [comment]
Did you also try to disable clear-on-join?
If you could upload a video that could visually show me what the issue is that would be great, or a test server that you are able to replicate the issue on so I could join and test it using the steps you provided.

However, if you disable clear-on-world-changed and clear-on-join and your items are still clearing it wouldn't be an issue with ItemJoin as those are the only functions that allow ItemJoin to clear any items.
