### ISSUE TITLE
[Request] flags - item-store for dispenser, dropper...

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#183]
Could you add more support type for flag "item-store" 
I tested lots of storage methods, but the following types are not included. 
- dispenser 
- dropper 
- armor stand
- donkey's packet
- llama's packet
Furthermore, can you create a new flags which bond to themselves.
So players weren't start to brush special ability items.
Thank you for fixed the flag placement last time, that is really helpful to me.
-----
This is the items file.
https://pastebin.com/txEyM6qS
--
Server version:  git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
ItemJoin version: 4.9 build#143

**Comment by RockinChaos** [comment]
Thank you for the fantastic and well-formatted request. 
This is simple enough for me to add so you will see it in the next version! I will post here once I have officially added it to a snapshot build so you will be up to date with the progress.

**Comment by RockinChaos** [comment]
Item-Store now supports dispenser, dropper, armor stand, donkey and llama packet/storage.
In addition, I have fixed a bug with item-store with non-block items in an item-frame instance.

Normally I would link the fixed snapshot and say it is safe to download, however, this feature has been pushed to the dev-branch that contains the new framework for ItemJoin which is extremely experimental and once complete will be uploaded for release on ItemJoin's spigot/bukkit pages.

So, for now, I will say this feature has been added and if you are interested in testing it you can try the latest snapshot in the dev-branch linked below. However, this is not recommended to use on public servers and should be used in a testing environment only, otherwise do so at your own risk.

I will post back and close this issue once the full release is posted on ItemJoin's download pages.
ItemJoin v3: build #12
Snapshot dev-branch; http://ci.craftationgaming.com/job/ItemJoin%20v3/


EDIT: I just noticed you also said;
Furthermore, can you create a new flags which bond to themselves.
So players weren't start to brush special ability items.

Can you elaborate on what you mean? I don't quite understand.

**Comment by RockinChaos** [comment]
This feature has been officially added in the release of ItemJoin v5.0.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=254085

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes

As for the second part; " Furthermore, can you create a new flags which bond to themselves.
So players weren't start to brush special ability items. "

If you wish to elaborate on this, being something that I missed feel free to re-open this issue and I will be happy to look into it!
