### ISSUE TITLE
[Support] add flags - Prevent craft items and Prevent anvil items

### ISSUE THREAD

**Issue by EnTIv** [RockinChaos/ItemJoin#184]
add two flags: Prevent craft items and Prevent anvil items

**Comment by RockinChaos** [comment]
So you are looking for a way to prevent ItemJoin items from being used in a craft recipe as well as prevent them from being repaired in an anvil?

**Comment by RockinChaos** [comment]
I have added the requested features for the use of an ItemJoin item being repaired and used in a crafting recipe.
The itemflags are as follows;
**item-craftable** - If the ItemJoin item is not allowed to be used in the crafting recipe, trying to place the item in the crafting table will automatically place it back into the player's inventory.
**item-repairable** - If the ItemJoin item is not allowed to be repaired it will cancel the action.
The item-repairable actually has two functionalities, the one listed above as well as if you put it on an item that is used in a "repair" recipe such as a diamond it will also cancel the repair action.


Normally I would link the fixed snapshot and say it is safe to download, however, this feature has been pushed to the dev-branch that contains the new framework for ItemJoin which is extremely experimental and once complete will be uploaded for release on ItemJoin's spigot/bukkit pages.

So, for now, I will say this feature has been added and if you are interested in testing it you can try the latest snapshot in the dev-branch linked below. However, this is not recommended to use on public servers and should be used in a testing environment only, otherwise do so at your own risk.

I will post back and close this issue once the full release is posted on ItemJoin's download pages.
ItemJoin v3: build #13
Snapshot dev-branch; http://ci.craftationgaming.com/job/ItemJoin%20v3/

**Comment by RockinChaos** [comment]
This feature has been officially added in the release of ItemJoin v5.0.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=254085

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes
