### ISSUE TITLE
Flag item-store

### ISSUE THREAD

**Issue by Nedjii** [RockinChaos/ItemJoin#190]
1.) Last version
2.) Tacospigot 1.8.8
3.) I saw o the wiki that item-store is supposed to block the use of crafting table but it's not, it works for chest etc.
4.) https://paste.helpch.at/xucanaqule.coffeescript
5.) There is nor error.

**Comment by RockinChaos** [comment]
Looks like the crafting table was a typo in the wiki. 

However, I have added the crafting table to this latest snapshot and it is safe to download. I have tested it and it seems to be working as intended now.

I have also updated the formula for which the plugin tries to detect what object you are trying to store the item into which should now have a 100% accuracy and future expansion for new items! Previously I was using an inventory method which couldn't tell the difference between a crafting table and your own inventory because of the inventory type so now I am using an object type detectable.

Download here; http://ci.craftationgaming.com/job/ItemJoin/156/

This will be available in the full release of ItemJoin v5.0.0.

**Comment by RockinChaos** [comment]
This feature has been officially added in the release of ItemJoin v5.0.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=254085

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes
