### ISSUE TITLE
Disallowed Inventory Movement Only On Menu Items

### ISSUE THREAD

**Issue by xSparky911x** [RockinChaos/ItemJoin#2]
Would like to see it only disallow movement on the items that are being used. For example when in creative mode working on our spawn I can not add other items to blank spaces in my hot bar. I understand there is an OP bypass mode but I don't want to have to give op to anyone helping work on the hub.

Also when using placeable items to issue a command, like the brown stained glass for example, it places the block if you right click. Shouldn't this be disabled?

**Comment by XSilverSlayerX** [comment]
Thank you for using the Github issue tracker!

Currently I am working disallowing the movement for specified items instead of global so that feature will come soon.

No it shouldn't be disabled because I left it as vanilla. If you were in an instance of a player you wouldn't have permissions to build on hub so no item would be placed. I am working on a way to disable that though in the config.

**Comment by RockinChaos** [comment]
This feature is now in ItemJoin 2.3 and will be released in the next few days! I hope you enjoy!

Disallow Inventory Movement is now ItemJoin only items and are specifiable.
CreativeByPass & OpBypass are added.

A lot of issues with the placing items and commands have been fixed.
