### ISSUE TITLE
repopulating items?

### ISSUE THREAD

**Issue by SpelunkerSteph** [RockinChaos/ItemJoin#214]
Hey thanks for the wonderful plugin, ItemJoin.
I'm going to apologize if this is just lack of coding/programming knowledge on my part, however,
when I'm editing the default items that the  plugin comes with and save it, it creates a new yml file called items{random4-5digit number} I've even deleted the original and renamed the newly generated file items. At that point, it repopulates the deleted default items folder and that is the only one recognized upon server restart.
Thanks for your time,
Very Respectfully,
SpelunkerSteph

My info as per your request is as follows:
1.) ItemJoin v5.0.3
2.) Paper 1.13.2
3.) What is the problem that you are having? listed above
4.) Pastebin.com link for YAML: https://pastebin.com/SHGqnfEG
5.) N/A

**Comment by RockinChaos** [comment]
This question has already been answered in the resolution center; https://www.spigotmc.org/wiki/resolution-center/#config-file-s-resetting-not-saving

But in an essence its due to improper YAML configuration, meaning it could be a multitude of things such as bad spacing or incorrect characters, etc.

You will find these two links useful (As these will tell you what is wrong with your YAML file);
Paste the copied config file this into the following link; https://codebeautify.org/yaml-validator
You can also use this link but it's not as pretty as code beautify, however, code beautify will miss certain errors so use this if it continues to break; http://yaml-online-parser.appspot.com/


Taking a look at the generated YAML files you sent me, the default items were VERY messed up including the new ones, if you copy it into the YAML validator link you will see how many errors there are.

I have simply copied the first few items that didn't seem to resemble the default ones and fixed those for you; https://pastebin.com/GP4XFZPS

Also, make sure you are using a program like NotePad++ to edit YAML files (any other program except the default notepad).

Lastly, if you look at your console window when you reload ItemJoin or the server, you will notice it says generating a new items.yml (slightly before that) you will see the actual error and exactly where the YAML file is erroring out.

Sorry for YAML files being so complex, it is simply how they are designed and the Spigot API relies on them a lot.

**Comment by SpelunkerSteph** [comment]
Thank you so much! This helps a lot! I had no idea it was so finicky.
