### ISSUE TITLE
Color Pane will Cause TPS Sudden Loss on 1.14

### ISSUE THREAD

**Issue by Xuwznln** [RockinChaos/ItemJoin#218]
Both the latest dev build and spigot release version will cause the problem:
When the item (color glass pane) change the color, the server tps will drop to very low, and can notice obvious server lag.
There is no problem when on 1.12.2.
So Please fix that. Thanks!

**Comment by RockinChaos** [comment]
This is a known issue with Minecraft 1.14+ and is an issue with Mojang. Spigot is unable to implement a fix at the moment and there are no workarounds in the plugin side of this. We will have to wait until Mojang pushes out a fix for this.

Currently, 1.14 is very broken and the worst release that has been released to date with a lot of chunk loading bugs, client entity lags when looking at flowers, etc. Spigot so far has not officially released any version of 1.14 because of this underlying issues so please stay tuned until they officially announce 1.14.

**Comment by RockinChaos** [comment]
Just a ping -- I would check this again with the 1.14.4 release of Minecraft since this now contains A LOT of performance bug fixes. I have tested this with 1.14.4 and it seems to be working as intended. Please let me know.
