### ISSUE TITLE
Item not getting put in inventory

### ISSUE THREAD

**Issue by TheParsley** [RockinChaos/ItemJoin#230]
1.) 5.0.3.
2.) 1.12 Spigot
3.) Item not getting put in inventory. When command executed you get the error: "You do not meet the permission requirement to receive the item"
4.) Config: https://pastebin.com/ygUYmHP8 en-lang yml: https://pastebin.com/1rxzv5xR items yml: https://pastebin.com/LuALSSup
5.) No errors

**Comment by RockinChaos** [comment]
Pretty much means exactly what it states, you do not have the required perms to get the item.
In your config you have
`Permissions:
  Commands-Get: true`

Setting this to false will resolve the problem. Otherwise, players need to have the permission node to get the item since you also have Obtain-Item set to true (setting this to false would also resolve your problem if you don't want to use permissions). So in your case, it would be `itemjoin.compass.*` or `itemjoin.compass.HubWorld`

**Comment by TheParsley** [comment]
I'm very sorry. I literally figured it out 40 seconds after posting. Was about to take this down. Thank you for your prompt response.
