### ISSUE TITLE
Item click-through, version 3

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#238]
Spigot 1.15 (Jenkins 2517)
ItemJoin 5.0.6-b346
IronDoors 1.1

If I right-click my ItemJoin item (which opens a DeluxeMenus menu) while looking at an iron_door or iron_trapdoor, the door is toggled. I think that it should not be, given the cancel-events flag:
```
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
```
In my previous Skript version of open-door, I explicitly canceled the event (see #225). But apparently IronDoors doesn't, and I'm not sure that it should. Any ideas?

**Comment by SlimeDog** [comment]
On further testing, I think the issue is with ItemJoin. The same Skript has the same problem now, which used to work correctly.

**Comment by SlimeDog** [comment]
Any ideas about this? I'm stumped.

**Comment by RockinChaos** [comment]
Hey, yes sorry for the slow reply I have been fairly busy.
-- I have narrowed down the issue to be with Skript, I am unsure why so I have been trying to get in contact with the developer. I believe it has something to do specifically with the iron door whether the name for initialization has changed etc. In previous versions of Skript (with the latest ItemJoin version) this does not happen. But upon downloading the latest Skript version this issue appears.

**Comment by SlimeDog** [comment]
OK and thanks. If you can get that resolved, I will go back to using Skript. However, it is also a problem with IronDoors. Any ideas about that?

**Comment by RockinChaos** [comment]
Sorry for the slow reply, I would have to look at the plugin myself to see. Oddly I cannot find it for some reason :/

Could you link it please?

**Comment by SlimeDog** [comment]
[IronDoors 1.1](https://www.spigotmc.org/resources/irondoors.73022/history)

**Comment by RockinChaos** [comment]
Okay so, I can confirm this is an issue with IronDoors. Their event is setup without any priority which makes it difficult for other plugins to cancel the event to prevent it from passing to the other plugin, typically requiring us to put our event state to monitor which is against the conventional use.

It should also be noted that the event was also not being canceled because the event is being triggered twice since as of the Combat Update, the PlayerInteractEvent executes for both offhand and main hand at the same time. ItemJoin was only set to cancel the main hand.

If you want you can contact the developer for this fix;
Add a precheck to the code before it is run as; `if (!event.isCancelled())` however, this is a deprecated method and may not be supported for long.

Since IronDoors is open source I resolved the issue; https://www.dropbox.com/s/7t497ads0m24mye/IronDoors.jar?dl=0
ItemJoin snapshot for canceling both events; http://ci.craftationgaming.com/job/ItemJoin/361/

**Comment by SlimeDog** [comment]
Thank you for investigating and identifying the issue.

I confirm that the combination of the IronDoors and ItemJoin updates resolved the issue.

Please post a PR with the IronDoors fix.
