### ISSUE TITLE
[Bug] inventory-modify

### ISSUE THREAD

**Issue by matahombres** [RockinChaos/ItemJoin#239]
## Thanks for taking the time to open a feature/bug request!

**Once the following information is provided I will reply to you as quick as possible!**
1.) Latest
2.) Paper 1.12.2 build 1618
3.) Duplicate item
4.) Example: https://pastebin.com/wffWG6aj
5.) Nothing

When you push ctrl+number into one item have inventory-modify, this move position in ctrl+number and put into correct slot = duplicate

https://gyazo.com/7524aeecb144acdc78a092da5214ea83
ctrl+1 =
https://gyazo.com/0dc074f4ecdcb2f0925fbb99784f8c8f

**Comment by RockinChaos** [comment]
Sorry for the very late response to this. ItemJoin's popularity has really taken off and I am finding it hard to keep up with support. 

Confirmed as a bug and should be resolved now in this snapshot; http://ci.craftationgaming.com/job/ItemJoin/360/

**Comment by RockinChaos** [comment]
**This bug has been officially fixed in the release of ItemJoin v5.0.6.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes**
