### ISSUE TITLE
Rank Join Items

### ISSUE THREAD

**Issue by MrAcho420** [RockinChaos/ItemJoin#248]
1.)   V5.0.5
2.)   Lastest Spigot

I'm wondering if there is a way for join items but specific for a rank?

Thanks in advance !

**Comment by RockinChaos** [comment]
In a way yes. It takes a bit of work though so stay with me on this.
How you would want to do this is basically grant the players permissions for the specific ItemJoin items you want for each rank. 

To start you will want to set your `Permissions.Obtain-Items` to true in the config.yml so that it will require permissions for players to receive the items. See; https://github.com/RockinChaos/ItemJoin/wiki/Config.yml#obtain-items-false

Then you will want to give the players the proper permissions for the items individually so you can use the default permissions nodes see; https://github.com/RockinChaos/ItemJoin/wiki/Permissions#itemjoinworlditem

Which is essentially (an example); `itemjoin.world_nether.ultra-item`

OR if you want to do a single permission node for a group of items, create your own permission node. It can be anything but in this instance ill choose `itemjoin.rank1` then set for each item in the items.yml `permission-node: itemjoin.rank1`

See the second half of this explanation (for a better example of custom permission nodes); https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#establishing-itempermissions-required

Again make sure you give the players the proper permissions (so the groups the players are in) for the set of items you want for that rank.

Let me know if this did or did not make any sense.
