### ISSUE TITLE
Item does not exist

### ISSUE THREAD

**Issue by triggeredg** [RockinChaos/ItemJoin#264]
Hi,

I'm not getting a lot of errors in console around this, except "The item item_2 does not exist!" when I try to run the "/ij get" command. Although item_2 does exists, it's telling me that it doesn't when I try to get it. Happens both from console and in-game. Whenever I remove item_1 (another item), from my inventory, item_2 suddenly exists (if I specify the amount). I can use the command without specifying the amount, while I'm having item_2 in my inventory (with the ordinary feedback from plugin). This is either way. Can't seem to get what I'm doing wrong.

Pasting items.yml here:
https://pastebin.com/Fb1bb9sL

Pasting config.yml here:
https://pastebin.com/WbcCyJEG

Using version v5.0.5-RELEASE-b324 (latest version) on Craftbukkit git-Spigot-8faa8b4-7f6125 (MC 1.15.2-R0.1-SNAPSHOT) (latest version).

Thanks.

**Comment by RockinChaos** [comment]
You were incorrectly using the `probability` function for the items. If you do not intend to use it do not set it. Since both of them had 100% probability (and that is not the functionality of the probability) it made both of them have 50% probability. item_2 was not able to be fetched via `/itemjoin get` because it lost the dice roll for the probability.

I also noticed you are using FIRST-JOIN, do note that this only gives the item ONCE and the only way to get it again is via `/itemjoin get` if you do not want that remove it from your itemflags & triggers. Setting the `JOIN` trigger will give the item every time on join.

I also noticed some spacing issues in the YAML files. (I am unsure if this happened when copy/pasting to Pastebin but I fixed them for you).



Here is a fixed items.yml; https://pastebin.com/3qK4eSRs

and config.yml; https://pastebin.com/LnDjDpT7

**Comment by RockinChaos** [comment]
Marking this as answered, please reopen this if the issue persists.

ItemJoin v5.0.6 has been officially released.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
