### ISSUE TITLE
Item delay bug

### ISSUE THREAD

**Issue by JackOUT04** [RockinChaos/ItemJoin#288]
## Thanks for taking the time to open a feature/bug request!

**[ Resource Questions / Help and Support ]**
If you have a question or are seeking support for one of my Resources, please make
sure you reply with the proper formatting shown below.

**Once the following information is provided I will reply to you as quick as possible!**
1.) The version of the Resource. 
**5.0.6**
2.) Version of the Spigot / Craftbukkit / Cauldron / ETC
** 1.15.2**
3.) What is the problem that you are having? When 
**Today I've had a problem with the %player% placeholder when I changed items-Delay to 0, it only showed steve's head.**
4.) Post all your YAML / Configuration files, please include a Pastebin.com link.
**Need to know if it's a bug before I do that. But here's the items.yml https://pastebin.com/xskt2u6s**
5.) Post any error codes found in your console window if it pertains to this issue, please include a Pastebin.com link.
**No errors**

**Comment by TheRobLP** [comment]
Can confirm this.

**Comment by RockinChaos** [comment]
After some testing, this "seems" to be fixed in the latest snapshot.

Please let me know; http://ci.craftationgaming.com/job/ItemJoin/407/

**Comment by JackOUT04** [comment]
Still doesn't work for some reason.

**Comment by RockinChaos** [comment]
Frustratingly I am unable to replicate this issue since b407.

1.) Can you confirm you are running b407 by typing `/itemjoin` and checking if that is the build number that appears?
2.) Is your server a bungeecord server?
3.) If it is not a bungee server, is your server in offline or online mode?

**Comment by JackOUT04** [comment]
1) I confirm
2) Yes
3) Server in offline mode because I have bungeecord.

**Comment by RockinChaos** [comment]
So after a long time of consulting with other developers, I have determined this to be impossible to resolve. Since the server is running in offline mode it relies on BungeeCord to fetch the Players Skin to attach to the Skull. BungeeCord is hardcoded with a small delay when pinging the Mojang Website to get the Skin to prevent abuse of their URL. This means the item has to be given with a delay greater than the BungeeCord delay or the skin won't be rendered.

So the only suggestion I can give is to increase the `items-Delay` in the items.yml until the skin renders. I apologize that this is the only option and if the way that BungeeCord and Mojang handshake changes I will be sure to revisit this in the future.

**Comment by JackOUT04** [comment]
Ok, it works with 1 second delay which is good for me. Thanks for help!
