### ISSUE TITLE
Issue with items,

### ISSUE THREAD

**Issue by Yeronix** [RockinChaos/ItemJoin#292]
Hey there! As far as I can tell I've set up permissions, and items should be set to world, yet I can't seem to get them to show up in game.
I'm using Luckperms, Multiverse, and Lobbyapi.
In-game, Itemjoin doesn't seem to recognize there are any items at all, regardless of world. I'm trying to more or less create a lobby kit, that players are only given in that one world via either a join or world-switch trigger, but can't quite get it to work. 
Additionally, the /itemjoin menu command GUI hangs when clicking create, or attempting to add an item via the hopper.
The getall command returns that the player has all items, the remove command states they have no items, and the list command doesn't find anything either.
I can't upload the items.yaml but here's a [Pastebin](https://pastebin.com/7YmyuY5k), I mostly toodled around with what was there and tried to add my own.
Thanks for your time!

**Comment by RockinChaos** [comment]
Hi!
Thanks for taking the time to open an issue, I am happy to help you resolve this as quickly as possible.

A quick tip:
1.) You can check if permissions are correctly setup by typing `/itemjoin permissions` and `/itemjoin permissions 2` (the second page is for item-specific permissions. This will output your specific permissions and if you have perms for the item. These values are player-specific so having another player that is unable to obtain the items, type that command and tell you the output values (red/green checkmarks) will tell you their permissions.

-- The hanging issue with the menu has been officially fixed in the snapshot(s) so the latest snapshot contains this fix and is currently pending official release. If you are interested you can check out the dev branch here; http://ci.craftationgaming.com/job/ItemJoin/


When checking the Pastebin you provided me I notice some spacing issues, quite a few actually (which causes the YAML to fully error out). I also noticed some missing colon(s) which also would cause the YAML to error out. YAML files are tricky as they are very sensitive, sadly something I cannot avoid which is why I created the in-game editor. But in your case obviously it isn't working since it was hanging. 

While it is possible that these spacing issues happened when you copy/pasted into Pastebin I fixed them and tested it as working in this new Pastebin; https://pastebin.com/vUEzt7Sh
In the future, you can use http://yaml-online-parser.appspot.com/ to check for YAML errors by copy/pasting into the input box.

![image](https://user-images.githubusercontent.com/10971577/82404423-1a55a580-9a16-11ea-889f-a442de88a778.png)


Let me know if that new Pastebin resolved your issue. -- If this does and it starts to become an issue for you modifying the items.yml manually, I would really recommend downloading the latest snapshot, while it may contain a few bugs (so far tested without any bugs being found) it won't outright cause any major issues or break anything.

If it did not;

Please provide the following information so I can assist you further;
1.) Spigot Version.
2.) ItemJoin version, check the build number via `/itemjoin`
3.) Config.yml Pastebin.
4.) En-lang.yml  Pastebin.
5.) Please enable the debugging option in the config.yml and restart the server (checking for ItemJoin error codes) and send a Pastebin link if there are any.

Thanks again for reaching out!

**Comment by Yeronix** [comment]
Oh hey, that Pastebin worked! Leave it to my own ignorance to bork it up haha. Thanks so much for the in depth response! I'm not sure what happened with the YAML, but it all seems to be working now! Also, that parser is a life saver, thank you so much haha.

Thanks again (and thanks for such a great plugin!)
