### ISSUE TITLE
Add Frennch Localization Please :)

### ISSUE THREAD

**Issue by SashapounNako** [RockinChaos/ItemJoin#302]
I saw that we could ask to add a new language so here it is: I and surely several French people would like a French version. I can do the translation very well because I'm French (I can prove it to you if you want) and I've already translated several English -> French projects.
Thank you for your understanding.

**Comment by SashapounNako** [comment]
Here the first version of the language file in French https://cutt.ly/TiBx6MY

**Comment by RockinChaos** [comment]
Okay so I have added this to the latest snapshot, let me know if there are any issues: http://ci.craftationgaming.com/job/ItemJoin/439/

To generate the fr-lang.yml; set `Language` in the config.yml to `French`.

Additional Notes:
Apologizes for the dumb question as I do not speak the language--Is there a way to write certain words/phrases without using an apostrophe `'`? Example word/phrase: `n'avez`. I ask this as a single apostrophe in a word breaks any YAML file as they use it to identify the beginning and end of a String. For now, I have simply doubled the apostrophes so the YAML file doesn't break, it will appear in chat as a single apostrophe though, for example; `n''avez`.

Lastly, in the next version can you also translate the English notes that are presented following a `#` (they explain what certain messages do).

**Comment by SashapounNako** [comment]
Yeah no problem ! And thanks for respond me ^^

**Comment by SashapounNako** [comment]
Hello, where do I edit the file? Like before, I send a file, or else?

**Comment by RockinChaos** [comment]
This is where the file is located; https://github.com/RockinChaos/ItemJoin/blob/master/files/locales/fr-lang.yml

You could create a pull request and modify it through the github site but it might be easier for you to send me the lang file and I could manually make the changes. Either one works.

**Comment by SashapounNako** [comment]
That's it, I modified the comments to put them in French, and some lines hadn't been translated (I had forgotten them ^^') : https://cutt.ly/oow0haf

**Comment by RockinChaos** [comment]
Changes are now reflected in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/442/

(You will need to delete your old fr-lang.yml to see the changes).

**Comment by SashapounNako** [comment]
Sorry I still have an update of the file (I check little by little depending on my use), I still found some lines not translated and I replaced the "?" caused by the YML, by letters without accents. I don't know if it suits you but here is the [new version](https://cutt.ly/voPeFKu)

**Comment by RockinChaos** [comment]
Okay so, I am not sure if you are still using the old fr-lang.yml as when I copied the changes over you actually ended up un-translating lines that were already translated--for the most part they were the comments preceded by the `#`.

So I have only copied some of the changes, also I found a UTF-8 symbol for an apostrophe so I replaced the doubled apostrophes with the new UTF-8 single one as it doesn't cause any YML issues.

Also, it seems you wre having the "?" issue because you were still using a old YML that was not converted to UTF-8 formatting to allow these special characters. The link below has the YML converted to UTF-8 and the symbols seem to appear correctly--I want to keep these as the other languages use accents so I want to keep it consistent. 

Snapshot (remember to delete your old fr-lang.yml from the root ItemJoin folder `/plugins/ItemJoin` so that way it regenerates with the newly added changes; http://ci.craftationgaming.com/job/ItemJoin/470/

**Comment by RockinChaos** [comment]
This feature has been officially added to the release of ItemJoin v5.0.7.
You can grab it here; Download: https://www.spigotmc.org/resources/itemjoin.12661/download?version=354306

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
