### ISSUE TITLE
Item says unknown command

### ISSUE THREAD

**Issue by arhsj** [RockinChaos/ItemJoin#31]
I've bound a compass to the command /nav ('nav' in the config) which is supposed to open a ChestCommands GUI which gives navigation possibilities. When I right click the compass however, it says "Unknown command. Type "/help" for help." The strange part is that the command exists and that if I do /nav manually, the GUI comes up.

Here is an image of the item config:
![image](https://cloud.githubusercontent.com/assets/7833720/14771444/19569abe-0a59-11e6-8d24-21475754cedb.png)

**Comment by RockinChaos** [comment]
This is because nav is not a real command. Everyone gets this mixed up and that is why I hate ChestCommands. The commands created with ChestCommands are only useable by ChestCommands therefor any external plugins will not be able to execute the command.

Please use:

**cc open <file>	**

This opens any menu loaded by the plugin directly. You also need the permissions for the menu itself.

file is the name of the file that has the /nav command in it.

For more help on commands see:
http://dev.bukkit.org/bukkit-plugins/chest-commands/pages/tutorial/commands-and-permissions/

If you are still having problems feel free to re-open this issue.

**Comment by arhsj** [comment]
Now this is where I'm confused. Another plugin called CustomJoinItems which I previously used was able to do it. The only reason I switched from that plugin to this one was because I couldn't get it to give me the item when I join the server and only when I leave then re-join the world.

**Comment by RockinChaos** [comment]
This is because CustomJoinItems and ChestCommands are made by the same developer. They are both integrated together. Their code are not open source so I have no way to integrate ChestCommands into my plugin.

The reason I created this plugin was lack of support for CustomJoinItems. I had the same issue as you I also had multiple world support issues.

Its a simple fix though all you have to do it make ItemJoin execute the command cc open filename

**Comment by arhsj** [comment]
Do you happen to know a way to prevent it from saying "Opening the menu "navigation.yml"." when it executes cc open filename?

**Comment by RockinChaos** [comment]
Sorry for such a late reply I have just been very swamped. I have not been able to look into this. I know there is a way but I forget how. I was able to disable this on my server but it was such a long time ago. It should be located either under the global config as a true/false statement or under each menu yml.

If that fails to work you can try to just remove the message entirely by editing the messages/lang.yml
