### ISSUE TITLE
Item-spamming not work

### ISSUE THREAD

**Issue by juancruzdal** [RockinChaos/ItemJoin#322]
Plugin Version: ItemJoin-5.0.7-SNAPSHOT-b491
Server Version: Paper 1.8.8

Console log: No console errors

Error desc: I can hold the interact button and execute the action two times

**Comment by RockinChaos** [comment]
Okay, so the `items-Spamming` boolean was originally created to stop the spamming of items that were ItemCommands defined with a cooldown duration and a cooldown message. As well as items such as Ender Pearls to prevent spam right-clicking them all in a micro-second launching them all essentially at once.

I have now tweaked it so that it also prevents spamming items with commands defined without a cooldown or cooldown message. (I assume this was the issue you were having as you didn't provide your items.yml).

Please let me know if this resolves your problem; http://ci.craftationgaming.com/job/ItemJoin/497/

If it does not, please post your items.yml in a pastebin.com link and a clear description of how you are interacting with the item.

Let me know!

**Comment by juancruzdal** [comment]
Solved

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.7.
You can grab it here; Download: https://www.spigotmc.org/resources/itemjoin.12661/download?version=354306

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
