### ISSUE TITLE
Get command doesnt work as normal

### ISSUE THREAD

**Issue by LilUziMiln** [RockinChaos/ItemJoin#341]
## Thanks for taking the time to open a bug report!

**Describe the bug**
When I do /ij get item player 1 it gives the item to myself and not to the player

**To Reproduce**
No warnings

**Expected behavior**
Get the item in to players inv and not in mine
**Screenshots**
/
**Pastebin**
/

**Please complete the following information:**
 - Resource Version and Build Number: 5.1.1-SNAPSHOT-b574
 - Server Version MCpaper 1.16.2

**Additional context**
Just something weird, would be handy if its get fixed. I know their is no support for 1.16.x but just wanted to let you guys know, otherwise plugin works fine on my server so far

**Comment by RockinChaos** [comment]
Hi, can you clarify what command you are using? You say `/itemjoin get 1` but that isn't a valid command.

Do you mean `/itemjoin get Ultra RockinChaos 8` gives it to yourself `LilUziMiln` for example (the executing player)?

**Comment by LilUziMiln** [comment]
yep, <> messed up my cmd sorry

**Comment by RockinChaos** [comment]
Perfect working on a fix for this now.  Also quoting " I know their is no support for 1.16.x" -- I am not sure where you got this idea, as ItemJoin v5.0.7 was the version that was released several months ago fully supporting 1.16.x so it's been a few versions since then that we have supported 1.16. Also, the front page of ItemJoin shows this as well. If there is something I need to change please let me know as I was to make sure everyone knows 1.16 is supported.

**Comment by LilUziMiln** [comment]
Oops sorry, thought it wasnt supported anyway thanks for quick reply

**Comment by RockinChaos** [comment]
Should now be fixed in the latest snapshot; https://ci.craftationgaming.com/job/ItemJoin/576/

Let me know!

**Comment by LilUziMiln** [comment]
Yup, its fixed TY
