### ISSUE TITLE
Duplicating item on relogging?

### ISSUE THREAD

**Issue by AngryJebus** [RockinChaos/ItemJoin#35]
Hi, I've found an issue (I think). I have an item for each world that goes into slot 5 in the inventory. If a player moves that item into another slot, then disconnects and joins again, they get another item in slot 5, but still keep the original item in the slot they moved it to. It wouldn't be too much of an issue; however if a player has a different set of items (e.g. diamonds) in slot 5 before they disconnect, those items get deleted. I'm not too sure how to solve this?

items.yml: http://pastebin.com/uW4X5r9Y
config.yml: http://pastebin.com/kPFc4Pc6

**Comment by RockinChaos** [comment]
First, this bug has been noted and fixed in v3.0 once it is released.

Second, yes, If there is an item in the slot an item is assigned to and it is NOT similar to the item defined it will remove the item in slot 5 and add the item in config to slot 5. I have added something in the new v3.0 that will be released called an Arbitrary slot. This will put the item/items defined in the config into the first available slot in the inventory. If there is no available slot you will not get the ItemJoin item. This Arbitrary slot prevents the loss of "player items" and will not overwrite any items the player currently has.

**Comment by AngryJebus** [comment]
Lovely! Thanks for the response, and thanks for a fantastic plugin! Keep up the good work :)

**Comment by RockinChaos** [comment]
v3.0 has been uploaded and will be approved shortly!
