### ISSUE TITLE
Help w/ giving food on join

### ISSUE THREAD

**Issue by Malum-In-Se** [RockinChaos/ItemJoin#366]
I am trying to give food (bread) on join, but I keep getting back:  "The item bread-item does not exist."

I know I must be missing a value, such as hunger or saturation, but I just can't find a example entry to copy.  Here's an excerpt from the items.yml:

  bread-item:
    id: bread
    slot: 10
    count: 64
    name: '&dBread'
    triggers: first-join
    enabled-worlds: asgar

I really appreciate the help.  I tried very hard to find the answer w/o bothering you.  All my other "give" items went thru fine.  Awesome plugin, a must have for servers and definitely one the first ones that needs to be installed.

**Pastebin**
 - I didn't copy the files because it seems to be a simple answer, but I just can't figure out this one.

**Please complete the following information:**
 - Resource Version and Build Number: itemjoin v5.0.6
 - Server Version:  paper 1.16.4

**Additional context**
 - none

**Comment by Malum-In-Se** [comment]
btw:  the spacing didn't copy correctly above for the yml entry, but I do have it right in the yml.

**Comment by RockinChaos** [comment]
So this looks to be properly set up, I tested using v5.0.6 and wasn't able to replicate it.

I would suggest updating as v5.0.6 is quite outdated;
Link; https://ci.craftationgaming.com/job/ItemJoin/660/
**Remember to remove your old ItemJoin.jar file.

One thing that could cause this issue is an improperly listed enabled-world.
You can test this by setting `enabled-worlds` to ALL and if it functions properly then you know its an improperly listed world name.

Example; `enabled-worlds: ALL`

**Comment by Malum-In-Se** [comment]
that was it re world name. you're so smart.  i can't really thank you enough, so i just sent you a donation.  i think you could easily charge for this plugin.  i'm definitely willing to support u.
