### ISSUE TITLE
Region-Enter does not work

### ISSUE THREAD

**Issue by Rakion988** [RockinChaos/ItemJoin#377]
I want my items to leave when leaving an enabled region, but they stay.

These are my .yml's

https://pastebin.com/NNTKn8Mg - Item.yml
https://pastebin.com/NiKpEJER - Config.yml

Nothing happens.

Also when i do /clear and i respawn or rejoin all my items return except my diamond sword my queue sword.

**Comment by RockinChaos** [comment]
Sorry for the late reply, took me a bit to realize, you have a typo on all your items.

You defined; `enabled-region` but its actually supposed to be `enabled-regions` which is why it isn't working. Once you do that it will work.

Do note; you ahjve JOIN, RESPAWN and WORLD-SWITCH which do not respect regions.
If you only want the item inside the listed region(s) I suggest removing all triggers except for `REGION-ACCESS` as this will function anytime the player moves or teleports into the enabled region rendering the prior listed triggers not needed.
