### ISSUE TITLE
Join items not showing

### ISSUE THREAD

**Issue by Miluek** [RockinChaos/ItemJoin#383]
Hello, I have a problem with item on join... Inventory is clear... Still same on default config and still same on my edited config.
When I first add the plugin only one item is showed in inventory, book (default config), after I clicked on book, the book disappeared... :/ Can you help me? Thanks...

**Comment by RockinChaos** [comment]
Hi, sorry you are having issues.

Can you please provide the following so I can help you further;
1.) Your server version found via `/version`
2.) Your ItemJoin Build Number (Example: b365) found via `/itemjoin`
3.) Even though you said they are the default there may be an issue with how they were generated, so can you provide both your config.yml and items.yml in pastebin.com links.

Once I get this information I will be able to get this figured out.

**Comment by Miluek** [comment]
Hello, I use Viaversion, is it problem?

Item.yml https://pastebin.com/4tC8RSBd

Config.yml https://pastebin.com/173v6ZEf

**Comment by RockinChaos** [comment]
ViaVersion is perfectly fine as that is completely client-based and has no real effect on the server itself.
I do need to know the actual native server version though, which can be found via `/version`

Also, can you type `/itemjoin world` in-game and tell me what it outputs?

**Comment by Miluek** [comment]
Okay, there is screenshot of the /version (All my servers have same version)...
[](https://multi-craft.cz/wp-content/uploads/2021/04/Snimek-obrazovky-2021-04-03-v-4.14.40.png)

**Comment by RockinChaos** [comment]
Sorry for the late reply, so from what I can see is that you do not have the proper enabled-worlds defined for your items hense why the book item disappears (as it is not allowed in a non-listed world) and the other items are not given because the world isn't listed.


So two options.
1.) Add `enabled-worlds: Economy` to your items. Items; https://pastebin.com/mNKfzQVF
2.) Add `enabled-worlds: ALL` to your items -- this will allow ItemJoin items in ALL worlds. Items; https://pastebin.com/49UsSzMY

Either of those two will work, I took the liberty of changing your items.yml for you so simply click the link you desire.
I suggest using Option 2 as it will make it easier for you but if you have worlds you do not want ItemJoin items in then use Option 1.

**Comment by Miluek** [comment]
It's working now! 🙂 Thank you...
 A have one more question, It's possible to make Compass without teleporting? I want only Compass icon without left and right click, I want just that player click (right and left click) in game (also in inventory too) to open my ChestGUI for server navigation... Thanks 🙂
