### ISSUE TITLE
Slimefun ancient alter compatibility 

### ISSUE THREAD

**Issue by Brickmaster122** [RockinChaos/ItemJoin#387]
My server the plugin there is no way to move the item. When you place things on the ancient alter though and pick it up it breaks it and the item goes into the next available slot 

Things you could do are 

1. Make it so the non-movable items can not be placed on an ancient altar in slime fun
2. 
3. 

## :compass: Environment (REQUIRED)

Slimefun4 - RC 21  and item join v5.2.1

 - Server software: 
 paper/spigot
 - Minecraft version: 
 1.16.5
 - Slimefun version:

**Comment by RockinChaos** [comment]
So after a lot of testing I would have to say this is a non-ItemJoin issue.

I will note that adding the `cancel-events` itemflag to the item prevents it from being placed into the ancient altar.
So for example your item could resemble; `itemflags: inventory-modify, death-drops, self-drops, placement, cancel-events`.

The cancel-events itemflag prevents any interaction with an object while holding the item which is why this works.

If this does not resolve the issue please feel free to re-open this.
