### ISSUE TITLE
Error when entering any commands /itemjoin"an internal error occurred while attempting to perform this command"

### ISSUE THREAD

**Issue by uhiha1dezmont** [RockinChaos/ItemJoin#433]
Hello, help me solve the problem.
when entering any commands from the plugin , 'ItemJoin' I get this error: an internal error occurred while attempting to perform this command

**Comment by RockinChaos** [comment]
I apologize for the late reply, I have been experiencing power outages due to a windstorm.

That is odd, I would need to see your config.yml & items.yml in a pastebin.com link.
I also would need to know your exact server `/version` a screenshot would be nice, as well as your ItemJoin version found via `/itemjoin` (if possible) alternatively you can use `/version ItemJoin`.
Lastly there should be a console error that appears after typing the command, if it doesn't try enabling debugging in the config.yml of ItemJoin and restarting. Then try the command again, there should most definitely be a console error.

**Comment by RockinChaos** [comment]
I am marking this a resolved due to inactivity, this issue is likely resolved in the latest release so I would start there.

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799
