### ISSUE TITLE
negive options with !

### ISSUE THREAD

**Issue by FakEEE14** [RockinChaos/ItemJoin#440]
hi

it's possible to add negetive nodes for permission, world and ...
in examples players ned permision like 
    permission-node: 'itemjoin.ultra'
but this time you do this
    permission-node: '!itemjoin.ultra'
to give the item to pepoles that don't have the permission
or
we have
    enabled-regions: region1, region2
    enabled-worlds: world, world_nether, world_the_end
we can do this
    enabled-regions: !region1
    enabled-worlds: !world
to include all worlds/region except the negtive one
placeholders and condtion already have this option by setting equal:false 

this open a lot of other ways to create and config stuff

**Comment by RockinChaos** [comment]
So for the enabled-worlds this is already filled with the new feature `disabled-worlds`. I can also add the same for enabled-regions (disabled-regions) instead of using a negate prefix.

As for the permission-node, this should be possible to implement but it may take some time due to the fact that I need to be sure I implement it in a way without breaking previously set permission-nodes from older versions of ItemJoin.

I will update you when I progress on this.

**Comment by FakEEE14** [comment]
awsome and coool
thanks
call me for any help you need

**Comment by RockinChaos** [comment]
Apologizes for the late reply, I missed your last comment.

That is intentional as the wiki is reserved for official release notes.
All features that are currently on the dev branch are located in the Devlog; https://github.com/RockinChaos/ItemJoin/wiki/DevLog

Once the release is live I push an automatic update to the wiki pages that reflect the Devlog changes.

**Comment by RockinChaos** [comment]
Wow! This is an old one, sorry it took so long to finalize this, it just happened to coincide with another feature I was working on so I was able to implement the same code for both features.

1.) disabled-regions has been added in the previous release so that one is covered.
2.) I have added the negative permissions option as you requested so you can specify `permission-node '!itemjoin.ultra.item'` which will ONLY give the item you do not have this permission OR if the permission is set but its set to FALSE.

Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~

Thanks for submitting this feature request and for being so patient!
