### ISSUE TITLE
NBT-related errors on 1.18

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#441]
## Thanks for taking the time to open a bug report!

**Describe the bug**
NBT-related errors when enabling items that were previously good.

**To Reproduce**
1. Import IJ configuration from 1.17.1
2. Install IJ 5.2.3-b783
3. No errors on server start-up until ...
4. Multiple errors per item in log
5. Items do not execute commands as before
6. `/ij getAll` gets items, but they are not active

**Log errors**
Repeated multiple times per item
> [22:16:57] [Server thread/ERROR]: [ItemJoin_ERROR] {ItemMap} An error has occured when getting NBTData to an item.

**Please complete the following information:**
 - Resource Version and Build Number: 5.2.3-b783
 - Server Version: Spigot-1.18-3335

**Additional context**
`config.yml` and` items.yml` available if needed

**Comment by RockinChaos** [comment]
Confirmed as an issue, been working on this one for a while.
There has been some MAJOR changes to the net.minecraft methods so its going to take a fairly long time for me to translate this and create an enum reflection for legacy & future Minecraft versions.

I can't be sure how long but I should have a working snapshot in a few days or possibly tomorrow.

**Comment by SlimeDog** [comment]
Thanks.

**Comment by RockinChaos** [comment]
Okay so, ItemJoin seems to now be functioning normally with the latest snapshot.
Please use caution when testing this build as I cannot fully confirm it is functioning without some testers. The next few builds should be more stable as I work to cleanup the code a bit. This is simply a proof-of-concept build to see if everything is functioning. Mojang/Microsoft changed the name of their methods in 1.18 MAJORLY so it broke pretty much everything since I use NMS for backwards compatibility. So assuming I got the names right everything should work, although I can't be sure since their code is now obfuscated as of 1.17.

Link; https://ci.craftationgaming.com/job/ItemJoin/784/
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by RockinChaos** [comment]
An updated build has been compiled containing optimizations to the previous code.
Link; https://ci.craftationgaming.com/job/ItemJoin/785/

No bugs have been found and this is likely going to be the current state for the 1.18 code unless any bugs are found.

**Comment by SlimeDog** [comment]
ItemJoin 5.2.3-b785 works for my admittedly limited use cases. Thanks.
