### ISSUE TITLE
keep on death duping items

### ISSUE THREAD

**Issue by ryantheleach** [RockinChaos/ItemJoin#453]
When people die with the keep on death flag, it resets the count of the item they are holding.

**Comment by RockinChaos** [comment]
I am presuming you are the same individual from the Discord server. I am going to convert this to a feature request as I talked about.

Here is a direct link to the Discord convo (reference for myself); https://discord.com/channels/291764091239006208/429407613042556928/929206668829556836

**Comment by RockinChaos** [comment]
Okay sorry this took so long, this was a bit of a pain to implement.
Turns out the example you had shown on Discord only applied to PaperSpigot so I had to design my own work-around that functions for both spigot and paper.

The item will only be kept if it is currently in your inventory when you die.
This also works well with the auto-remove itemflag as if you respawn in an area that the item is not in an enabled-world of, it will be automatically removed.

Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**
