### ISSUE TITLE
On equip On unequip command 

### ISSUE THREAD

**Issue by Whyteer** [RockinChaos/ItemJoin#475]
Hello, your plugin is fantastic but i have found really bad bug.
So i wanted to give players boots that allow them fly only when they equip it and disable fly when they unequip.
Everything was fine except the fact that when someone equips boots and without leaving opened inventory unequips it 
unequip command doesnt work and he still has fly on. Please fix it.

EDIT: I set custom item to equip command and un equip but when i left click or put item in furnacne or chest it also executes command
PLEASE FIX !

**Comment by RockinChaos** [comment]
1.) So it seems this issue is related to `items-Spamming` at the top of the items.yml. Please set this to true instead of false, you should notice it properly works now.
2.) Confirmed, was able to replicate the chest/furnace issue and provided a fix for this as well.

Link; https://ci.craftationgaming.com/job/ItemJoin/820/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=451699
