### ISSUE TITLE
Support Authme And AdvancedLogin

### ISSUE THREAD

**Issue by SofyanTauridOdeMadi** [RockinChaos/ItemJoin#478]
## Thanks for taking the time to open a feature request!

**Is your feature request related to a problem? Please describe.**
this is just an error in my authentication plugins such as AdvancedLogin and Authme every time it finishes authentication sometimes items from ITEMJOIN crash the server

**Describe the solution you'd like**
may support the plugin if the player has authenticated, itemjoin is immediately obtained

**Describe alternatives you've considered**
I don't think so

**Additional context**
Nope

**Comment by RockinChaos** [comment]
So I may need more context.
AuthMe is already supported; https://github.com/RockinChaos/ItemJoin/wiki/API-&-Dependencies#how-does-authme-work

As for AdvancedLogin, they do not appear to have an available API and it's a premium resource so I can't view their code to see if they do in fact have an API or not. Since AdvancedLogin does not document any API support I am unable to add support for it. However, AuthMe is already supported.
