### ISSUE TITLE
Global Items Option

### ISSUE THREAD

**Issue by altrisi** [RockinChaos/ItemJoin#48]
I have a server with lots of lobbys (not bungee) and I want to have the same items in more than one world. Can I do it without copying and pasting the item to the other world's config?

Thanks.

**Comment by RockinChaos** [comment]
This is not a feature implemented yet. You would have to copy, paste, and rename each world to set the exact same items.

I will work on adding a global-items feature.

**Comment by altrisi** [comment]
In that feature you will can set in what worlds (not all) the item will be given?

**Comment by RockinChaos** [comment]
Yes, this new feature will have two ways of working. You can define 1 global world. Which can be active for ALL worlds on the server.

Then the second option which can be defined is a global world that you define once, but you tell it which worlds you want the items to be allowed in.

Such as:

world-list:
- lobby1
- lobby2
- lobby3

global:
  items:
    first-item:
      id: 1
      name: 'Global Item'

so that now lobby1/2/3 would get global.

**Comment by altrisi** [comment]
Ok. Thanks.

**Comment by RockinChaos** [comment]
This has been added as of ItemJoin v3.5 and it has been released!

You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=107083
