### ISSUE TITLE
item in craft slot disappear after click

### ISSUE THREAD

**Issue by Yriokiri** [RockinChaos/ItemJoin#481]
## Thanks for taking the time to open a bug report!

**Describe the bug**
Updated server from 1.18.1 to 1.18.2, previusly everything worked fine, when i updated i noticed that every time i click an item in the crafting slots it disappear after use.

**To Reproduce**
1. get the items
2. Click on it
3. reopen inventory
4. no errors in console

**Expected behavior**
item should not disappear

**Screenshots**

BEFORE

![Screenshot_63](https://user-images.githubusercontent.com/77204889/169669154-bc437df3-2246-43f8-bc01-aa2bbfe1e0a2.png)
AFTER
![Screenshot_64](https://user-images.githubusercontent.com/77204889/169669156-3ad063c4-3799-4d48-8fd5-eca3fd51e0e8.png)

**Pastebin**
items.yml: https://pastebin.com/4CA8NA5r
config.yml: https://pastebin.com/hNNdthzU
plugin list: https://prnt.sc/IYivR1HnY9VW

**Please complete the following information:**
 - Resource Version and Build Number: [v5.2.4-RELEASE-b822]
 - Server Version [git-Paper-336 MC:1.18.2]

**Comment by Yriokiri** [comment]
update: after i removed CMI it won't happen.

**Comment by RockinChaos** [comment]
Hi, I apologize that this is a late update.
I can confirm it's CMI. I have several open tickets on Discord referencing similar issues as well as a few others but I cannot find a way to fix it at this time. Since CMI is premium I cannot test it directly and it seems the issues are rooted in CMI's code due to their priority not being set to a lower level. This makes it so CMI takes priority over ItemJoin so I am unable to prevent this action from happening.


I am still continuing to work on this but I wanted to give you an update so you don't feel left out.

**Comment by RockinChaos** [comment]
So unfortunately I am going to have to mark this as will-not-fix as the issue entirely lies with CMI and isn't something I can fix on ItemJoin's side of things. I put in multiple requests to the developer with no response so I am pretty much out of ideas. They need to implement an API reference specifically for this issues as well as make their event priorities more plugin friendly as they get the final say in what happens so I can't prevent it from ItemJoin.

I hope that makes sense. I would suggest trying to get in contact with the CMI developer, but since I haven't heard anything from them in over 2-3 months I don't think you will be able to reach them.

Again I apologize :(
