### ISSUE TITLE
I have a few issues

### ISSUE THREAD

**Issue by Gameridaily** [RockinChaos/ItemJoin#483]
I don't have a code issue. I just have issues with when i make new recipes the game registers it as a normal recipe. And i have tried for hours to make it work but no luck. Anyone have advice?

**Comment by RockinChaos** [comment]
Looks like I can't reply on Discord since you have outsiders blocked.

I don't entirely understand your issue. What you described is exactly how ItemJoin functions, recipes are registered into the game itself that way if say ItemJoin crashes or errors out the recipes still work. These recipes are cleared on server startup and re-set again through ItemJoin.

All NBT data associated with an ItemJoin item (if that is applicable in said recipe) will be required to craft.

Does that make sense?


If you can clarify your issue and provide a snippet of your item in question so I can get some insight into what you are trying to explain that would be great!

**Comment by Gameridaily** [comment]
Well now i have to wait till 1.19 update. Please work on it i hate these new errors <3
