### ISSUE TITLE
Error spamming console oon join

### ISSUE THREAD

**Issue by LOCNetwork** [RockinChaos/ItemJoin#484]
## Thanks for taking the time to open a bug report!

**Describe the bug**
This error happens when joining the server, this error spams the console

**To Reproduce**
1. Join the server

**Expected behavior**
The error does not show

**Pastebin**
https://pastebin.com/wW3VwaPm

**Please complete the following information:**
 - Resource Version and Build Number: [Latest version]
 - Server Version: [Spigot-1.8.8]

**Comment by RockinChaos** [comment]
Looks like your ItemJoin version is out-of-date.
v5.2.4 is the current release version which contains a very similar bugfix.

The latest snapshot is currently on v5.2.5. I would suggest updating to the latest snapshot since it is stable.
Link; https://ci.craftationgaming.com/job/ItemJoin/835/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=467409
