### ISSUE TITLE
[ItemJoin] Task #2508498 for ItemJoin v5.2.5-SNAPSHOT-b842 generated an exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by curkan** [RockinChaos/ItemJoin#488]
**Good afternoon.** At some point, ItemJoin starts to give an error and fills the logs every millisecond. This allows access to the server.
Tried different versions, change items. Nothing helps.

**config** - https://pastebin.com/XdAr8vbD
**items.yml** - https://pastebin.com/G7KQcf6A
**Error log** - https://pastebin.com/vucmEbbe

 - Resource Version and Build Number: _v5.2.5-SNAPSHOT-b842_
 - Server Version - _Patina 1.18.2_

**Comment by RockinChaos** [comment]
So I can't quite seem to replicate this. You have a fairly simple configuration so there shouldn't be any reason a repeating task is spamming your console.

Is it possible to provide me with a full server log of this error? I need the stack trace that is sent at the very beginning of this issue to track down the bug as all the error log you provided shows me that there was an error with a repeating task.

**Comment by shuiqing2046** [comment]
> So I can't quite seem to replicate this. You have a fairly simple configuration so there shouldn't be any reason a repeating task is spamming your console.
> 
> Is it possible to provide me with a full server log of this error? I need the stack trace that is sent at the very beginning of this issue to track down the bug as all the error log you provided shows me that there was an error with a repeating task.

`[20:38:35 WARN]: [ItemJoin] Plugin ItemJoin v5.2.5-SNAPSHOT-b845 generated an exception while executing task 6478634
java.lang.NullPointerException: null`
It seems that I also get a similar error
There is no change in configuration from 1.16.5 to 1.19.1, only the ItemJoin version is upgraded

**Comment by RockinChaos** [comment]
Still isn't what I am looking for.
The provided info doesn't tell me anything other than ItemJoin is throwing a NullPointerException somewhere in the 150k lines of code.

I need either the stack trace which is a big chunk of garble that contains numbers to direct me to a specific line where the error is occurring, OR I need the full server log so I can find it myself.

When an error is spammed repeatedly it eventually silences the stack trace which is why it's not appearing in the screenshots, it would be back at the beginning of the server startup.
(This is also assuming you have debugging enabled in the config.yml of ItemJoin)


So I need either
1.) Stack Trace
or
2.) Server log file

In order to continue resolving this issue.
I hope that makes sense~
