### ISSUE TITLE
Help with NBT

### ISSUE THREAD

**Issue by SirCraftypants** [RockinChaos/ItemJoin#494]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detain you can.**
I'm trying to get the NBT to work for the custom item plugin i use named Itemsadder.

![2022-08-23](https://user-images.githubusercontent.com/66942713/186204113-7fef3544-56b2-4be4-bc08-d57266f1cdc3.png)

**Pastebin**
Even if it is not related to the problem, please include ALL configuration files in separate Pastebin.com links. This way if we need to help you modify any of these configuration files we will already have them handy.

I've tried:

`  nbt-item:
    id: STICK
    slot: 33
    properties: 'TranslatableDisplayName:player_menu_stone, Slot:33, Plugin:itemsadder'
    count: 1
    triggers: world-switch, respawn     
    enabled-worlds: Lobby, towny, towny_nether, towny_the_end       
`

**Please complete the following information:**
 - Resource Version and Build Number:      ItemJoin-5.2.5-SNAPSHOT-b847 

 - Server Version [e.g. Paper-1.19.2

Any help would be appreciated!

**Comment by SirCraftypants** [comment]
OK I got the custom texture to load by using `model-data:` but the nbt isn't working

`  nbt-item:
    id: STICK
    slot: 1
    count: 1
    model-data: 143
    properties: 'TranslatableDisplayName:Player Menu Stone, Slot:33, Plugin:itemsadder'     
    triggers: join, world-switch, respawn     
    enabled-worlds: Lobby      `

**Comment by RockinChaos** [comment]
Ironically my latest update to the snapshots may have accidentally implemented a feature for adding the itemsadder information.
The latest snapshot contains the ability to add nested nbt data which is what it seems itemsadder is using.

Don't quote me on this as I am not 100% sure this will work since I don't know their exact nbt layout but given what you provided in the screenshots the nbtdata should be as follows;

```
properties: 'itemsadder:[id:player_menu_stone#namespace:customitems]'
```

You will need the latest snapshot for this to work;
Link: https://ci.craftationgaming.com/job/ItemJoin/849/
**Remember to remove your old ItemJoin.jar file**

**Comment by SirCraftypants** [comment]
sorry been unwell, i will test this later today.
