### ISSUE TITLE
ItemJoin_ERROR

### ISSUE THREAD

**Issue by Patryk-Suchecki** [RockinChaos/ItemJoin#498]
After entering the server, the player receives information such as on ss:
![image](https://user-images.githubusercontent.com/92213744/189333831-e3e6e2ff-5637-4469-8307-4018cca8a79c.png)

My configuration:
items.yml - https://pastebin.com/2iXDf9Af
config.yml - 

Console error - https://pastebin.com/raLi8VB0

Plugin version: 5.2.5-RELEASE-b850
Server: PurPur 1.18.2

**Comment by RockinChaos** [comment]
Okay, so this now appears to be fixed in the latest snapshot.
If you continue to experience issues please send me your `/itemjoin dump` output and I will be able to progress further on a fix.

Please let me know!~
Link; https://ci.craftationgaming.com/job/ItemJoin/879/
**Remember to remove your old ItemJoin.jar file**
