### ISSUE TITLE
Can't click on item in inventory in Gamemode Creative

### ISSUE THREAD

**Issue by Askarionn** [RockinChaos/ItemJoin#504]
## Thanks for taking the time to open a bug report!

**Describe the bug**
"Inventory" option to click on a item in inventory it's not working in gamemode creative

**To Reproduce**
1. Add the "inventory" option to an item
2. Click on it in gm 0

**Expected behavior**
Should execute the command you've set

**Screenshots**
https://youtu.be/Jp8PFKeUlUA

**Pastebin**
Even if it is not related to the problem, please include ALL configuration files in separate Pastebin.com links as well as any related error codes from the console window.

**Please complete the following information:**
 - Resource Version and Build Number: 5.2.6 b855
 - Server Version 1.19.2

**Additional context**

**Comment by RockinChaos** [comment]
This is intended, not a bug.

If you have the inventory-modify itemflag on an item and enter creative mode you will have your inventory force-closed.
This is to prevent exploits as creative mode breaks the inventory-modify flag as Mojang did not properly program their creative interface.

This is a known issue with many plugins so I simply opted to disable item interaction entirely. I would recommend using a creative mode alternative if it is super imperative such as FakeCreative.

Otherwise removing the inventory-modify itemflag will also solve this.

I hope that answers your question and I apologize that there is not a better solution. I am watching Mojang's dev branch so if they end up ever patching the many bug requests in regards to this issue I will be sure to update ItemJoin respectively.
