### ISSUE TITLE
New command action and flag + bug

### ISSUE THREAD

**Issue by Daniil6622** [RockinChaos/ItemJoin#523]
Hi.
1. Item flag "item-modifiable" doesn't work if player quickly took off his armor and put it an the anvil. After which he can modify item. I would like to suggest instead of banning the placement of this in the anvil slot cancel forging event.
2. I would like to suggest adding in this item flag (or separately) prohibition of use grindstone and command action "item is broken"

Server Version: Paper-1.19.3

**Comment by RockinChaos** [comment]
I confirmed the issue and it is now fixed in the latest release, in addition, I added the grindstone as requested.

Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=494934
**Remember to remove your old ItemJoin.jar file**

If you continue to experience issues feel free to open a new issue and include the `/itemjoin dump` information.
