### ISSUE TITLE
Annoying message

### ISSUE THREAD

**Issue by SaltyPotata** [RockinChaos/ItemJoin#540]
### Server Version

Paperspigot 1.16.5

### Resource Version

Itemjoin 6.0.1

### Dump Information

Unknown command.

### Describe The Problem

[ItemJoin] {ItemHandler} An error has occured when getting NBTData to an item, reason: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_16_R3.NBTBase.clone()" because the return value of "java.util.Map$Entry.getValue()" is null. (2)

### Additional Context

Everytime someone joins this message pops up. I just want to delete this. I see no issues only this annoying message.

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
So I need the dump info to continue this help request.
Since you submitted "unknown command" as your answer you definitely are not using ItemJoin v6.0.1 as I implemented it in v6.0.0 so you are using an outdated version which could likely be the cause of your error message since it looks semi-familiar from a while ago.

I suggest updating and providing the `/itemjoin dump` info if the message continues.

Latest;
https://www.spigotmc.org/resources/itemjoin.12661/download?version=495066

Also you ticked one too many boxes in your checklist :)
