### ISSUE TITLE
Books with clickable text don't work

### ISSUE THREAD

**Issue by MaxJoker149** [RockinChaos/ItemJoin#556]
### Server Version

Paper 1.20.1

### Resource Version

ItemJoin-6.0.3-SNAPSHOT-b910.jar

### Dump Information

https://pastebin.com/wKH12v4T

### Describe The Problem

The first book with clickable text that is delivered after the server restarts works fine, but after that the books that are delivered to players stop appearing with clickable text, they stop working...

### Additional Context

![2023-10-22_02 30 25](https://github.com/RockinChaos/ItemJoin/assets/23411638/6dc0f42e-2ce2-44aa-9006-a27211624607)
![2023-10-22_02 30 30](https://github.com/RockinChaos/ItemJoin/assets/23411638/96fd6ee3-7680-4e44-8612-8465c2e32d81)

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Confirmed, turns out the Legacy method for book pages was being activated on all versions. Since it is executed every-time whereas the JSON is executed once it was being overwritten after the first book was given.

A proper version check has been implemented and has now been tested as working.
Thanks for the report!

Link; https://ci.craftationgaming.com/job/ItemJoin/912/
**Remember to remove your old ItemJoin.jar file**
- If you get an error when loading the webpage give it a refresh a few times.
