### ISSUE TITLE
Problem on world-changed give

### ISSUE THREAD

**Issue by tom2090** [RockinChaos/ItemJoin#56]
(my english is bad)

Hi! I had an problem, on world-changed, when this flag give items. When i create an other world like this:

> lol:
     items:
      9:
       id: SKULL_ITEM
       name: '&a%player%'
       skull-owner: '%player%'
       data-value: 3
       lore:
         - '&6Bienvenue &a%player%!'
       itemflags:
         - 'world-changed'

(i use notepad++, but bug into github, cant past the spaces.)

This is not do effect on the "lol" world, i dont receive the item. Nothing on the logs. My server turns on 1.8.8 with 2.4 version. HELP!

**Comment by RockinChaos** [comment]
This is because version 2.4 does not have itemflags. This was added in the later versions of ItemJoin.

ItemJoin is FULLY backwards compatible, Meaning ItemJoin v3.5 for Minecraft 1.10 will work flawlessly for Minecraft 1.8.8.

Just download ItemJoin v3.5 and the world-changed itemflag will work.
https://www.spigotmc.org/resources/itemjoin.12661/download?version=107086

Let me know if this resolved your problems, Also Please NOTE: ItemJoin will generate brandnew config files and you will have to add your items accordingly to the new config files generated. Its fairly simple :)

**Comment by tom2090** [comment]
So, i do to change my server version, this is not what i wanted :(

**Comment by tom2090** [comment]
The plugin not works correctly on 1.8.

**Comment by tom2090** [comment]
So, i changed the version, but, now, the items not appears on the world "Hub"...

**Comment by RockinChaos** [comment]
I am a little confused on what you mean, you do not have to change the version of your server to run ItemJoin v3.5. It will run on Minecraft v1.8.

Can you do this for me,
1.) Explain what you are trying to do in detail.
2.) Explain what is actually happening ("the bugs")
3.) Link me your items.yml, config.yml & en-lang.yml by posting them at pastebin.com and sending me the links to each one of them
4.) Send me any errors in console if there is any.

Once you provide me these answers I will be able to proceed. Thank you :)

**Comment by RockinChaos** [comment]
Fixed as of v3.6 and can be downloaded here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=107393

I tested it on v1.8.8 and it works flawlessly for me. This should be the fix you are looking for :).

If you have any other problems feel free to open another issue.
