### ISSUE TITLE
Cannot load from object array because "contents" is null

### ISSUE THREAD

**Issue by VacAge** [RockinChaos/ItemJoin#582]
### Server Version

git-Purpur-2155

### Resource Version

6.0.6-SNAPSHOT-b973

### Dump Information

https://ci.craftationgaming.com/dump/?id=tonayobeja

### Describe The Bug

When the player logs in, he writes an error
https://mclo.gs/cmEsHtc

### Expected Behavior

No warning...

### Steps To Reproduce

-

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Hi, thanks for the report! I tried replicating using your configuration but I was unable to produce the error.
Since the error is pretty clear I produced a fix that should resolve the message.

Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~
