### ISSUE TITLE
Please list the changelog items by build number

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#593]
### Describe The Feature

The changelog currently lists all changes for `ItemJoin-v6.0.6-SNAPSHOT` releases. Unless I save a copy of the previous list for comparison, I cannot tell which items were added for the latest build (in this case, `6.0.6-SNAPSHOT-b987`. Please separate the changes for each build.

### Expected Solution

Changelog separated by build.

### Describe Alternatives Considered

None

### Checklist

- [X] I have read the wiki to make sure my request has not already been implemented.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my feature request is unique and another request does not exist.

**Comment by RockinChaos** [comment]
I know this isn't what you're asking for but in the meantime, you can access https://ci-dev.craftationgaming.com/job/ItemJoin/ and view the builds individually to see the changes.

Ironically I am actually in the middle of moving my projects to a different workflow which happens to incorporate a per-build breakdown. Though currently, I have been setting it up to list all changes in a single changelog but hyperlink to which build they were added in. I'll consider adding a separate list of changes for each build. These changes are intended to go into effect on the integration site https://ci.craftationgaming.com/ which will out-right replace the Dev Log listed on GitHub. I am mainly doing this because I have to manually update the current dev log which is a pain and burns a lot of time which is why even now it's still not up-to-date with the latest snapshot changes. So putting in an automated system helps me help you lol.

Hopefully, that explains what direction I am headed in.

**Comment by SlimeDog** [comment]
Thanks.
