### ISSUE TITLE
Console Item Error

### ISSUE THREAD

**Issue by FraikqL** [RockinChaos/ItemJoin#600]
### Server Version

Pufferfish 1.20.4

### Resource Version

v6.0.7

### Dump Information

https://ci.craftationgaming.com/dump?id=hutodocisi

### Describe The Problem

when you press PCM on the subject and a menyuk comes out, an error appears in the console, everything functions on the server.
![browser_EAWZdnTwkw](https://github.com/user-attachments/assets/b19ca248-9795-4ef6-9705-0711b1cd3c5c)

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Sorry for the late response, I can't recall if you asked this in the Discord server as well.

This is **not** a bug. To prevent this error you must prevent the consumption of the book via `cancel-events` itemflag.
To be clear this is not a bug, that error exists because it was specifically coded to happen by Mojang. If you get a knowledge book from creative mode the same issue will appear because they are null books (you don't learn anything from consuming them).

https://github.com/RockinChaos/ItemJoin/wiki/troubleshooting#-knowledge-book-issues

**Comment by FraikqL** [comment]
thanks!
