### ISSUE TITLE
Item Duplication With Chest Sort

### ISSUE THREAD

**Issue by TylorTurner** [RockinChaos/ItemJoin#606]
### Server Version

1.20.4

### Resource Version

v6.0.7

### Dump Information

g

### Describe The Bug

Using the "Double-Right-Click outside inventory" duplicates inventory items. 

https://www.spigotmc.org/resources/chestsort-api.59773/
![image](https://github.com/user-attachments/assets/03b62838-0864-40d6-8e70-4c6788426775)

https://github.com/mfnalex/ChestSort/blob/master/HOW_TO_USE_API.md

https://streamable.com/060i0a

### Expected Behavior

Item to remain in inventory, currently it works fine with most features from chestsort and CMI clear.

### Steps To Reproduce

Make an itemjoin item
install chestsort plugin
open chest and use "Double-Right-Click outside inventory"

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Thanks for the video, very odd as ItemJoin items are explicitly denied any ChestSort functionality via the hook I made into their API; https://github.com/RockinChaos/ItemJoin/blob/a28bfa9dc26e31df815156c923fa632f7cb75f93/src/main/java/me/RockinChaos/itemjoin/listeners/plugins/ChestSortAPI.java#L39

Either something is borked with their API or I missed something that has changed.
Testing this now, I'll let you know what I find.

**Comment by TylorTurner** [comment]
Okay, thank you.

**Comment by RockinChaos** [comment]
Confirmed, seems to be a bug on their end as if you perform it *really* *really* slowly it works fine. It seems whatever they do handling their event can't keep up with the inventory contents they are returning.

I simply just fetched the player inventory manually instead of relying on their event and it seems to work perfectly fine now.
Thanks for letting me know!~
Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~
