### ISSUE TITLE
Error on join

### ISSUE THREAD

**Issue by KhrysAK47** [RockinChaos/ItemJoin#610]
### Server Version

Paper 1.20.4

### Resource Version

6.0.7-RELEASE-b995

### Dump Information

https://ci.craftationgaming.com/dump?id=docafeteca

### Describe The Bug

Error when players join the server. https://imgur.com/a/vKclvU2

This error also happened on other versions of ItemJoin, including last one. 

### Expected Behavior

The error should not be present.

### Steps To Reproduce

N/A since the error started happening randomly, I haven't modified ItemJoin in over a week.

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Odd that is just started happening, did you happen to update your server version recently?

I see that the error is referencing and it seems I have made some changes since then that potentially have already resolved the issue. The latest release of ItemJoin is v6.1.0 and the latest snapshot (v6.1.1) also contains some bugfixes.

I would suggest updating to the latest snapshot to see if that resolves your issue.
Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

You can see the changes made since v6.0.7 here; https://www.spigotmc.org/resources/itemjoin.12661/update?update=560606

Let me know!
