### ISSUE TITLE
variable %hitplayer% doesn't work

### ISSUE THREAD

**Issue by llaurenss** [RockinChaos/ItemJoin#63]
Item:
[img](https://puu.sh/r9HxH.png)
Example:
[gif](https://puu.sh/r9Hv6.gif)

btw everytime someone joins, leaves or dies my server gets a lag spike
[timings](https://timings.spigotmc.org/?url=yiposevube)

**Comment by RockinChaos** [comment]
I am currently looking into this but it may take me a day or two, about a month ago my raid array for my hard drives failed ( containing the ItemJoin code ) and I have sense ordered new parts and they will be here tomorrow and I will be able to rebuild my array and access the ItemJoin code.

I will post back here in about a day when I have further updates to this bug.

**Comment by RockinChaos** [comment]
This is because you were in creative mode, the even that triggers the hit player variable did not detect any damage attempting to be made to the player so it stayed the default one.

I have sense changed this to player interact event so it will now always work. This fix will be uploaded with v3.7.

I will post back when v3.7 is released.

**Comment by RockinChaos** [comment]
ItemJoin v3.7 has been released and you can get it here;
https://www.spigotmc.org/resources/itemjoin.12661/download?version=115467

Thank you for opening a ticket and if you still need help feel free to re-open this issue and comment back here.
