### ISSUE TITLE
Group items

### ISSUE THREAD

**Issue by mixerrules** [RockinChaos/ItemJoin#7]
Basically items for different ranks (group manager)
Ex: admin spawns with a book called admin panel, but vip spawns with a jet pack

**Comment by RockinChaos** [comment]
This is something I have been looking into doing. It will defiantly end up altering the config a lot in the future. I'll continue integrating this but it may not be out for a while.

**Comment by RockinChaos** [comment]
This has been added as of ItemJoin v2.7! Okay so here is how it works. Each item can have its own specific customizable permission node now. So! All you have to do it setup the item using the new configuration methods and give the custom permission to the right group (the group you want to get that item) and define the slot then boom! You got yourself an item.

This is actually really good because you can now set it so in the world HUB for example can have multiple items with the same SLOT set. Yet you can define them to only be given to certain groups using the custom permission nodes.

Let me know if you have any problems or need some help with this!

**I plan to release ItemJoin v2.7 tomorrow so look out for it!**
