### ISSUE TITLE
Server Crash Due to ItemJoin

### ISSUE THREAD

**Issue by SioWolf** [RockinChaos/ItemJoin#72]
I've already contacted you on Spigot, so I apologize for the duplicate post - but here is the official report:

My server has been crashing recently, once a day - always at random times.

Here is my error log from today: http://pastebin.com/xifyETxS
And yesterday: http://pastebin.com/e6jT4pk7

If I'm reading it correctly, it has something to do with ItemJoin. Although, I've never had to read these before.

ItemJoin config: http://pastebin.com/9TZ3Wzs4
items.yml: http://pastebin.com/LAz4tNiC

**Comment by RockinChaos** [comment]
Its all good, These issues will be corrected with the v4.0 release. i have been working desperately hard on it for the past few months and when I get into the testing phase I will let you know, if you want to take part in it I will defiantly provide you a snapshot.

Your issue might possibly be fixed with the v3.9 upload that I am going to release in the next few days, I will test it but v4.0 is a complete rewrite that is fixing a lot of duplicate looping scenarios so it will be a much better solution.

In essence a quick fix might be out in the v3.9 soon. I will keep you updated as I continue on this.

**Comment by RockinChaos** [comment]
Not expecting a reply from you just working on some final testing to see if I can fix the lag. How many players did you have when when the server crashed? Can you provide a full (date).log file of the day it crashed?

**Comment by SioWolf** [comment]
From what I can recall it didn't seem to correlate with how many players were online. I want to say we crashed once or twice with less than 10 people online. Unfortunately, I don't have those logs anymore.

**Comment by RockinChaos** [comment]
ItemJoin v3.9 has been released and fixes this issue.
You can download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=139837
If you have anymore problems feel free to open another bug report.
