### ISSUE TITLE
ItemJoin Crasht my server :(

### ISSUE THREAD

**Issue by ItsMennyo** [RockinChaos/ItemJoin#89]
I have found an error that I thought it was another plugin but someone had found the ItemJoin was therefore... https://gyazo.com/c6693f1589e3bd0cf63d864e9d262cd0

Big error: http://pastebin.com/XmB1RBZR

(Spigot)
ItsMennyo said: ↑
    Okay I'll figure it ff. And I found a false posetive. I use AntiKnockback but then I get kicked for Velocity.
    It did not crash log file, but I find this... http://pastebin.com/XmB1RBZR
Your server is crashing because of ItemJoin plugin, not because of Spartan.

**Comment by RockinChaos** [comment]
the crash is indeed from itemjoin, this is already a known issue if you check the earlier bug reports on github. I have already isolated the issue and (since I personally cant get my server to crash from itemjoin) I have no idea if it actually fixed it. I just went off of the error reports and fixed the lines of code on those specified lines.

**Comment by RockinChaos** [comment]
I have worked on a fix for this and I believe that this should fix your crashing issues. I could not replicate the crashes myself so I did a fix with the error codes you provided me.

**Comment by RockinChaos** [comment]
Update has been released, you can get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=147427
