### ISSUE TITLE
Massive Lag even after update.

### ISSUE THREAD

**Issue by Roadhog360** [RockinChaos/ItemJoin#90]
icJukeBox, WorldEdit, FrameProtect, WDLCompanion, JoinCommands, GroupManager, Antibots, ArcadiaJoin, Boost, WardrobePlus, WorldBorder, NametagEdit, BuycraftX, FakeMessager, Votifier, VoidSpawn, WorldGuard, BungeePortals, PluginReloader, InventoryLock, IPWhitelist, FeatherBoard, Tablist, Vault, ProtocolSupport, MyCommand, Essentials, VoteSend, Citizens, ChestCommands, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, ViaVersion, ProtocolLib, FurnitureLib, DiceFurniture, ClientStats, HolographicDisplays, LeaderHeads are my plugins. Even after the lag fix update, the plugin causes the server's TPS to drop and quickly die when more than one player is on.
NO other plugin does this, it only happens when ItemJoin is installed on the server.

**Comment by RockinChaos** [comment]
Unless you can show me some timings that actually shows that ItemJoin is lagging the server then its definitely not ItemJoin...

I had testers work on this for a few weeks with timings and the lag was reduced to literally none, even dropping the timings below Vault, meaning ItemJoin lags less than Vault does.

My theory is you have something incorrectly setup with your sever either lacking cpu or ram. I have my main server with 300+ people on it and only 6gb of ram on a amd 4 core cpu at 4000mhz. I get no stutter and no lag with this latest update.

So sorry unless you can show me a timings report, I can't really escalate this issue any further.

**Comment by Roadhog360** [comment]
I will make timings when I'm not as busy, then.

**Comment by Roadhog360** [comment]
Still haven't got time, but I'll make it clear that my server is correctly set up.
How much RAM does this plugin need? My hub only has 1GB.

**Comment by RockinChaos** [comment]
Thats fine and uhhh... If your running on 1 GB you better only have ItemJoin and 1-2 players online cus running 1 gb on a hub server is like running DOOM on a potato. Otherwise if you have a bunch of plugins along with ItemJoin and a few players logging into the server your defiantly going to lag, that would explain why your server is lagging and adding ItemJoin probably making you reach your point in max plugins for the ram you have.

You should have like 6-8gb of ram for a proper test. I run about 6 (5.5gb) of ram on my hub server allowing the plugins to take up about 3 gb of ram and then the other 3 are to handle the 150 players constantly joining and leaving my hub server.

**Comment by Roadhog360** [comment]
I have never had problems with a GTA server having multiple players on and that server had 80 plugins, no lag. I don't understand why your plugin needs a preposterous amount of RAM just to work BY ITSELF. This plugin is unoptimised, and with you saying ItemJoin needs more RAM, I can safely say I am no longer interested in this plugin. There were many more plugins which did far more than merely just give items and they never lagged me with multiple heavy-duty plugins on an 80-plugin server while many players were on.

**Comment by RockinChaos** [comment]
Lol fine by me, I literally stated my plugin uses less ram than most of the plugins you are using but okay. Minecraft is RAM intensive and you will find this out later when you continue to have the same problems down the line. Im not sure if your saying GTA as in a server type or GTA as in Grand theft auto the game by rockstar, cus you cant compare the rockstar game to minecraft, I am assuming you mean a gamemode type since I dont think you can even host a rockstar server.

If you seriously run 80 plugins on a singular 1 gb of ram with 10-20 players on it, I will give you a freaking award and ask to see this because I have 42 plugins on my hub server it uses 3gb of ram at IDLE. Even removing ItemJoin, and since I did develop the plugin I know its not interfering with any RAM usage, as I did state that It uses less than 1 mb of RAM, and there is 1024MB in 1 GB. Want proof that 1 GB is too little for a CB/Spigot server? Did a simple google search and read this; http://minecraft.gamepedia.com/Server/Requirements/Dedicated Straight from minecraft themselves, and those are VANILLA requirements not modded "CB/Spigot".

Anyways, try bumping up your RAM by 1 gb, and see if you stop lagging, like seriously, how can you not spare 1 more gb? Unless your running on a potato which then explains a lot.

Also I would love to see the timings, so feel free to post them when you get time because I have my timings and it shows ItemJoin using less than Vault and im pretty sure your server has Vault so my plugin isnt the problem unless you can prove it to me.  Simply adding my plugin and saying its lagging your server doesnt make it my fault, just allocate more RAM. I also assume you are new to hosting servers?

**Comment by SlimeDog** [comment]
1GB RAM is insufficient for a Spigot server, as noted above. I have absolutely no lag on Spigot 1.11.2 latest plus 77 up-to-date plugins, including ItemJoin. According to top and Statscraft, Spigot+plugins is allocated more than 1GB. So I would predict that your server is similar, and Spigot is swapping with other running processes (plus the operating system), which will certainly introduce lag. 

Recommendation + prediction: RAM is cheap. Buy some, several GB. Install it. Lag issues will be resolved.

**Comment by SlimeDog** [comment]
Have a look at [http://minecraft.gamepedia.com/Tutorials/Setting_up_a_server#Less_than_1GB_free_RAM](http://minecraft.gamepedia.com/Tutorials/Setting_up_a_server#Less_than_1GB_free_RAM)

**Comment by Roadhog360** [comment]
If you're comparing those statistics to me, SlimeDog, then you clearly didn't read my above post.

**Comment by SlimeDog** [comment]
@Roadhog360 I read your post in detail. If you insist on trying to run in 1GB, there is nothing more we can do. If you want help, ... well, no, you obviously don't, or you would find the time to do the requested trials over the last ten days.

**Comment by RockinChaos** [comment]
@Roadhog360 he isn't just comparing those to you, its every god damn server! You obviously either have no idea how to run a server or your just here to cause problems. There is nothing wrong with ItemJoin and you have had PLENTY of time to show evidence proving otherwise. ItemJoin takes up less ram than 3 of your top plugins in your server combined. Just because you finally hit your limit on ram by adding 1 simple plugin and complaining about lag with 1 GB of ram makes no sense, when you add another plugin in the furutre your still going to have lag, legit almost every game takes up more than 1 GB of ram and I am talking about the base platform you play on, the server side of games is a whole other story. Java is a RAM hog and you really have no idea. Take the advice that has been given to you, you have had plenty of time to post evidence rather than complain and I have came to the conclusion that you are just here just to troll. This issue has been resolved.

**Comment by RockinChaos** [comment]
First off I'm not being a "coward" you are just trolling as I have looked into your profile and see that you post bullshit things and I'm not the only one having problems with you.. I gave you PLENTY of time to send my timings and you still didn't provide them after you saying you would several times. Several of us tried to help you but you don't understand how to run a server, I have been doing this for 7 years and I have more knowledge than you do and I also provided proof with my statements showing that my statements are **facts** and Mojang themselves tell you to use more than 1gb of ram.

You refuse to accept my help, its not my fault, as well as at first I was trying to be nice but you throwing accusations after I constantly prove that what I am saying is fact is starting to piss me off. Where is your proof? You still have yet to post any timings, that would be your proof.

Post your timings and we can be done with this.

**Comment by Roadhog360** [comment]
https://68.media.tumblr.com/6d3b4f56a9fcfa321419bcc60435b1d1/tumblr_inline_nriezvFvgo1qkpnrw_500.gif
I'm not replying to this, a waste of effort. I'd rather just post my timings, wear a smile, and then the party at fault will apologise for the trouble, and we can all have a good day.
Unless you want me to respond to your above post. I certainly will. I don't want to start a fight again so that's why I chose not to reply, even though some of those things you said sort of made me annoyed, but I'm still willing to forget ItemJoin and the past dispute you gave me as besides my lag, it is really the best plugin of its kind and I hope if you can't solve me issue, 4.0 does. No matter what happens in reply to the timings, I'll tear down my rating and wait for 4.0.

Timings:
Just me: https://68.media.tumblr.com/6d3b4f56a9fcfa321419bcc60435b1d1/tumblr_inline_nriezvFvgo1qkpnrw_500.gif
Me + Alt: https://68.media.tumblr.com/6d3b4f56a9fcfa321419bcc60435b1d1/tumblr_inline_nriezvFvgo1qkpnrw_500.gif

**Comment by RockinChaos** [comment]
I appreciate the mature response, I have taken a look at your timings and I know its not what you want to hear but it is indeed your server overloading from (general use) its actually not lagging from any plugins surprisingly.

To debug the timings this is whats going on;

At the very top it identifies that it is indeed showing your server is overloading with this message;
**Your server is lagging because it is overloaded (99%+ Server Load). Try reducing View Distance if it is above 4.**

What is causing your server to overload? 
1.) Connection Handler (This is the player pinging the server before, and the very second they click join.)
2.) Full Server Tick (This is entities dropped on ground, and mobs etc.) Just general use of the server.

I'm actually very surprised that your plugins are doing as well as they are I was expecting the overload to peak on a certain plugin but all your plugins are at basically zero PCT, meaning lag.

What does this mean? I am afraid to say that you really do need to expand your ram no matter how difficult it is. (This isn't tested but I'm pretty sure if you were to have brand new generated worlds vs the ones you are currently using, the server wouldn't overload because there is no chunks in the new worlds. They all have to be newly generated.)

As for ItemJoin v4.0, it will indeed reduce lag as I have compared the timings from v3.9.3 to the v4.0 - SNAPSHOT its more than 90% reduced, but v3.9.3 is already at a very low PCT. Its just more of an optimization rather than an improvement since the lag is already basically gone.

**Comment by Roadhog360** [comment]
I can't really expand my RAM, but I can say it's also not Citizens because for some reason ItemJoin was still doing this before I added it.... (I also took a look at the timings and actually got really confused... I have no idea WHAT's lagging me any more. I can say it's not ItemJoin now, but we need to answer why it only happens with ItemJoin)
Huh, at this point I'm flat out baffled as to why the server lags ONLY when ItemJoin is on. All I can say is that I do hope for 4.0 to cause a fix, since some of my servers on the (Yes, still Low-RAM network) use 70-80+ plugins without issues... A lot of which are a lot bigger and more intensive than ItemJoin is... Am I breaking science here or something?
I'll fold, and say it's my issue for now. I'm sorry for the past dilemma.

Also, I'm going to respond to your other message as well. I DO NOT INTEND TO START A FIGHT BY REPLYING TO IT. PLEASE DON'T TAKE IT THAT WAY.

"First off I'm not being a "coward" you are just trolling as I have looked into your profile and see that you post bullshit things and I'm not the only one having problems with you..."
Yeah, sorry about calling you that.... And as for the other ratings, I just review plugins as to what I see fit. If it doesn't work as advertised or has issues, I give a lower rating. I do agree I've given a couple bullshit ratings in the past. I've had a few removed in the past but some authors are too inactive to remove their replies with me.

"I gave you PLENTY of time to send my timings and you still didn't provide them after you saying you would several times."
Yeah, I got a little caught up, in like, everything at once. I was actually trying to give myself time to, but a lot of IRL stuff decided to cover me at the time. My bad. Completely.

"Several of us tried to help you but you don't understand how to run a server, I have been doing this for 7 years and I have more knowledge than you do and I also provided proof with my statements showing that my statements are facts and Mojang themselves tell you to use more than 1gb of ram."
Yeah, see, I'm a little annoyed with this statement... I DO know how to run a server, I'm just poor and can't run a lot of RAM. I'm sorry that my poor-ness has caused this whole shitstorm, had no idea it was my RAM. I was dead set on you because nothing else has ever given me such a laggy server and it only happened when ItemJoin was enabled. As for the 1GB of ram thing, my hub only uses 1GB, so I can make my others use more on my dedi box. I don't see the need to have more RAM on a hub, but I like ItemJoin so if I can afford more RAM in the future, I'll definitely put more on the hub just for this if I need to by 4.0.

"You refuse to accept my help, its not my fault, as well as at first I was trying to be nice but you throwing accusations after I constantly prove that what I am saying is fact is starting to piss me off, as well as threatening me?"
Yeah, sheesh. I can agree I wasn't being very nice, however when did I threaten you?

"I can get you banned off of spigot permanently for doing that."
_pleasedontihavethementalstabilityofachickennugget_

**Comment by RockinChaos** [comment]
I wasn't calling out Citizens2 btw. I was saying none of your plugins are causing lag once so ever like they are VERY low, it surprises me to be honest. I'm not quite sure why adding ItemJoin causes lag as if it was a compatibility issue it is suppose to show up in the timings because you can't mask any lag that ItemJoin produces. 

I understand what you mean by not being able to afford much I was pretty much in the same boat until I started going to college. The timings speak for themselves though on whats lagging you so you shouldn't get confused, the red indicates what is causing your server to lag (stating the obvious I know xD). 17tps isn't horrible though my setup causes me to run at about 18 tps normally without any lag or latency its just once your drop below 15tps it starts to become a problem, what is the **major issue is your server is overloading**, which is completely different from the tps.

I personally can't tell you exactly what this issue is beyond it not being any of your plugins as I don't have the exact same setup as you and its pretty impossible to replicate unless I go out and by the same parts. I can only suggest to add more ram. 

But as I said before it is very possible that adding ItemJoin was just the little tipping point that caused your server to start lagging. Kind of like a domino effect, of jenga, You stack something tall enough eventually it becomes unstable and that last block you place can cause everything to fall. - Terrible Enallage I know xD.

As for when I was saying that you were threatening me, in my perspective it was kind of like you were saying re-open the thread or else, but it doesn't matter to me tbh.

Sorry I can't fix this for you, If I was a magical genie I would defiantly do so. If you have any other issues with ItemJoin feel free to open up another issue, I am always wanting to help.

Have a good rest of your day :)

**Comment by Roadhog360** [comment]
I was just saying you should reopen the thread so I could send you my timings, I didn't mean to sound threatening, damn it. Did I sound threatening somehow? Sorry about that.
Also, I'd be happy to help you by reporting issues, but not only is a recode coming which may not even have said issues, but as you have seen, my server doesn't seem to want to accept ItemJoin into its plugins.

You have a good day, though.

**Comment by Roadhog360** [comment]
Hey, do you have a Discord or Skype account? Just curious.

**Comment by RockinChaos** [comment]
I personally don't use skype because I don't like my ip getting traced :P 
But I have actually been looking into getting discord, I am working on setting up a discord server for ItemJoin as well as a jenkins server (for snapshots/beta builds) upon the release of v4.0.

**Comment by Roadhog360** [comment]
Discord is really good, it's got everything Skype does (Pardon video sharing), boatloads more secure, and has everything TeamSpeak does, and is free.
Also, I like making Discord servers, I'll help with an ItemJoin server for Discord if you want.

**Comment by RockinChaos** [comment]
I have created the ItemJoin server a few days ago and I put my friend in charge setting it up while I work on programming v4.0. Which is such a pain to do while taking college exams for the next two weeks... but education is worth it.

Thanks for offering though.

**Comment by Roadhog360** [comment]
Okay. And sorry for being that way during your college time.

**Comment by RockinChaos** [comment]
Its all good, I was acting crappy too, been really stressed with college so it didn't really help my self control xD

**Comment by Roadhog360** [comment]
But me being a general dick probably led you to that. Don't take any blame.
