### ISSUE TITLE
Item Overwrite Safety feature (Enable it by default)

### ISSUE THREAD

**Issue by Techno3600** [RockinChaos/ItemJoin#94]
I was so happy to get a good plugin for my server. But you guys already created items which is cool but you did not put # in front of it. As a result half of my players inventory got deleted and I am very mad. Please put the "#" in front of the already created items.

Thanks
Anand

**Comment by RockinChaos** [comment]
I'm confused can you try and show me what you are talking about? Are you meaning your previous config was overwritten with the default items because of a version update?

**Comment by Techno3600** [comment]
I mean when you install the plugin there is pre-made items which don't have "#" in front of them, as a result they replace anything in the inventory hot bar deleted the whole hot bar.

**Comment by RockinChaos** [comment]
Literally a # can mean anything, are you meaning infront of every variable in the items.yml or in the item name?

I assume your not happy that examples were being shown by putting the items in the players inventory. On the front page of the documentations it is suggested to use a test server to configure the items as I currently have not added a feature that disables over-writing items. 

In v4.0 I have programmed in a safety-overwrite feature that is enabled by default so you don't accidentally wipe your items, which can be set to false to overwrite items once you configure it.

Slot Arbitrary currently is the only slot id that doesn't overwrite items as specified in the documentations. Sorry you had this issue but nobody until now had a problem with this and I will make sure in the future versions this is disabled by default. 

Are you using this on a hub server? I am asking because usually hub servers don't have items to get overwritten as the inventory is usually empty upon joining (via configuration of other plugins).

**Comment by RockinChaos** [comment]
Offically added to the v4.0 recode. It is called items-Overwrite and it is enabled by default. False = Items will not overwrite. True = items are allowed to overwrite.

![magic2](https://cloud.githubusercontent.com/assets/10971577/24736250/b7942aaa-1a3b-11e7-986a-d7154acf4377.png)


As you can see I did not receive any of the default items because the slots the items are suppose to go in are full, (0-9). Hope this is the outcome you wanted and I will reply back when I am ready to release the update.

**Comment by RockinChaos** [comment]
v4.0 has been released with this feature added!

You can click here to download; https://www.spigotmc.org/resources/itemjoin.12661/download?version=168950

**Comment by Deernose** [comment]
plzz an flag to do not show this message

**Comment by RockinChaos** [comment]
> plzz an flag to do not show this message

No flag is needed, simply remove the message from the lang.yml file and it will not be sent.
