### ISSUE TITLE
Shift+LeftClick can move item to the chest

### ISSUE THREAD

**Issue by RokkoEffe** [RockinChaos/ItemJoin#95]
I can press Shift+LeftClick to move custom item to the chest or enderchest, even if "inventory-modify" and "self-drops" item flags are set.

**Comment by RockinChaos** [comment]
What version of ItemJoin & spigot/cb are you using?

Also is this creative mode or survival mode?

**Comment by RokkoEffe** [comment]
I'm using CraftBukkit (Spigot) 1.11.2-R0.1-SNAPSHOT
ItemJoin v3.9.3

This bug is only in creative mode.

**Comment by RockinChaos** [comment]
Ah I had a feeling, this bug is client sided. I have to find a cheat to resolving creative mode issues, for some reason spigot refuses to cancel creative mode events properly like they do in survival mode.

I will try to find a work around for this but it might take a while as its not an itemjoin bug rather it is a spigot bug.

**Comment by RockinChaos** [comment]
v4.0 has been released with this issue fixed!

You can click here to download; https://www.spigotmc.org/resources/itemjoin.12661/download?version=168950
