### ISSUE TITLE
Lag & Random Item

### ISSUE THREAD

**Issue by InferiorBeing** [RockinChaos/ItemJoin#96]
The plugin is very useful and has all the features I need, except it **_SEVERELY_** lags my server :( Also, for some reason players get a gold shovel when they join even though it's not in the items.yml. Other than these issues, the plugin is **_fantastic_**! Thanks :)

**Comment by RockinChaos** [comment]
Can you post your items.yml, config.yml and en-lang.yml

How many plugins are you running?

What are your system specs? (Mainly CPU/GPU & RAM).

How many players do you usually have on your server?

How many players does it take to start noticing lag on your server?

What version of ItemJoin are you running & What version of spigot/cb?

Is It possible for you to send me a timings? Showing that ItemJoin is eating up a bunch of resources?

Try removing ItemJoin and checking if your server lags again over the next 2hrs / or however long it took to lag your server before.

I'm not quite sure why you are having this issue, I had some bug testers run ItemJoin on a potato computer for a couple weeks and it never ended up lagging them. I find it really strange because I run the latest ItemJoin & spigot and my hub server has 300+ people on it and no lag atm.

As for the golden shovel, that has nothing to do with ItemJoin, if its not in the items.yml then it is virtually impossible to have ItemJoin give you one as it creates the item from the item.yml, checking if each variable is there and grabbing the ID/Material. If none exists then it doesnt give the item.

With this info I should be able to begin testing and resolving your problem.

**Comment by RockinChaos** [comment]
Hey, just checking in are you still having issues with this? If you could provide some info I can get right on this ASAP and figure out what the problem is.
