### ISSUE TITLE
Skull, does not take the form of the owner

### ISSUE THREAD

**Issue by Techno3600** [RockinChaos/ItemJoin#97]
Hi,

The skull does not take the form of the owner, Here is the link to my items configuration
<https://pastebin.com/Jq4ZWSJ7>
Thanks
Techno3600

**Comment by RockinChaos** [comment]
Yeah I know what you mean, the skull-owner occasionally bugs out and doesn't render the skull owner correctly. This is an issue with mojang sadly but **I think I have found a hacky way to fix it** by sending packets to the player forcing mojang to send the skin of the player head. I will see if I can get a patch out soon, if not it will defiantly be in v4.0 sorry about this issue. I have been talking to some other developers about it and they were just as stumped as I was xD.

**Comment by RockinChaos** [comment]
Just an update I have "fixed" this for v4.0, however it will not be perfect. There was some optimizations I added to make it render more of the time but it wont work every time, it just depends on your server and or location. Sadly its an issue with Mojang and they haven't patched it yet because to render skins you have to request them from the Mojang servers and sadly it doesn't work all the time.

In my testing I only had issues sending requests to Mojang on the server first boot. Meaning each time the server is fired up after /stop, Someone (anyone) has to join the server once then anyone that joins after that will have the skin render, you can also join then leave and join again and the new item that is given would be a fixed skin head.

I responded to the open bug request that Mojang has and hopefully they will get with fixing it. This isn't a bug within the Minecraft versions its within their server. Once they fix it any version from Minecraft 1.8 to the latest will have the fix. (basically any version with the heads in them). This meaning none of the code changes in the Minecraft versions since its server-based not client-based.

Hopefully this info was useful I spent way to much time on this but it was getting on my nerves that I didn't have the answers at the time.

**Comment by Techno3600** [comment]
Awesome, thanks dude!!

**Comment by RockinChaos** [comment]
v4.0 has been released with this issue fixed!

You can click here to download; https://www.spigotmc.org/resources/itemjoin.12661/download?version=168950
